// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="passthrough,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.268000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=442,HLS_SYN_LUT=759,HLS_VERSION=2019_2}" *)

module passthrough (
        video_in_TDATA,
        video_in_TKEEP,
        video_in_TSTRB,
        video_in_TUSER,
        video_in_TLAST,
        video_in_TID,
        video_in_TDEST,
        video_out_TDATA,
        video_out_TKEEP,
        video_out_TSTRB,
        video_out_TUSER,
        video_out_TLAST,
        video_out_TID,
        video_out_TDEST,
        ap_clk,
        ap_rst_n,
        video_in_TVALID,
        video_in_TREADY,
        video_out_TVALID,
        video_out_TREADY
);


input  [7:0] video_in_TDATA;
input  [0:0] video_in_TKEEP;
input  [0:0] video_in_TSTRB;
input  [0:0] video_in_TUSER;
input  [0:0] video_in_TLAST;
input  [0:0] video_in_TID;
input  [0:0] video_in_TDEST;
output  [7:0] video_out_TDATA;
output  [0:0] video_out_TKEEP;
output  [0:0] video_out_TSTRB;
output  [0:0] video_out_TUSER;
output  [0:0] video_out_TLAST;
output  [0:0] video_out_TID;
output  [0:0] video_out_TDEST;
input   ap_clk;
input   ap_rst_n;
input   video_in_TVALID;
output   video_in_TREADY;
output   video_out_TVALID;
input   video_out_TREADY;

 reg    ap_rst_n_inv;
wire    Block_proc_U0_ap_start;
wire    Block_proc_U0_ap_done;
wire    Block_proc_U0_ap_continue;
wire    Block_proc_U0_ap_idle;
wire    Block_proc_U0_ap_ready;
wire   [9:0] Block_proc_U0_img_1_rows_V_out_din;
wire    Block_proc_U0_img_1_rows_V_out_write;
wire   [10:0] Block_proc_U0_img_1_cols_V_out_din;
wire    Block_proc_U0_img_1_cols_V_out_write;
wire    AXIvideo2Mat_DMA_U0_ap_start;
wire    AXIvideo2Mat_DMA_U0_ap_done;
wire    AXIvideo2Mat_DMA_U0_ap_continue;
wire    AXIvideo2Mat_DMA_U0_ap_idle;
wire    AXIvideo2Mat_DMA_U0_ap_ready;
wire    AXIvideo2Mat_DMA_U0_start_out;
wire    AXIvideo2Mat_DMA_U0_start_write;
wire    AXIvideo2Mat_DMA_U0_video_in_TREADY;
wire    AXIvideo2Mat_DMA_U0_img_rows_V_read;
wire    AXIvideo2Mat_DMA_U0_img_cols_V_read;
wire   [7:0] AXIvideo2Mat_DMA_U0_img_data_stream_V_din;
wire    AXIvideo2Mat_DMA_U0_img_data_stream_V_write;
wire   [9:0] AXIvideo2Mat_DMA_U0_img_rows_V_out_din;
wire    AXIvideo2Mat_DMA_U0_img_rows_V_out_write;
wire   [10:0] AXIvideo2Mat_DMA_U0_img_cols_V_out_din;
wire    AXIvideo2Mat_DMA_U0_img_cols_V_out_write;
wire    Mat2AXIvideo_DMA_U0_ap_start;
wire    Mat2AXIvideo_DMA_U0_ap_done;
wire    Mat2AXIvideo_DMA_U0_ap_continue;
wire    Mat2AXIvideo_DMA_U0_ap_idle;
wire    Mat2AXIvideo_DMA_U0_ap_ready;
wire    Mat2AXIvideo_DMA_U0_img_rows_V_read;
wire    Mat2AXIvideo_DMA_U0_img_cols_V_read;
wire    Mat2AXIvideo_DMA_U0_img_data_stream_V_read;
wire   [7:0] Mat2AXIvideo_DMA_U0_video_out_TDATA;
wire    Mat2AXIvideo_DMA_U0_video_out_TVALID;
wire   [0:0] Mat2AXIvideo_DMA_U0_video_out_TKEEP;
wire   [0:0] Mat2AXIvideo_DMA_U0_video_out_TSTRB;
wire   [0:0] Mat2AXIvideo_DMA_U0_video_out_TUSER;
wire   [0:0] Mat2AXIvideo_DMA_U0_video_out_TLAST;
wire   [0:0] Mat2AXIvideo_DMA_U0_video_out_TID;
wire   [0:0] Mat2AXIvideo_DMA_U0_video_out_TDEST;
wire    ap_sync_continue;
wire    img_1_rows_V_c_full_n;
wire   [9:0] img_1_rows_V_c_dout;
wire    img_1_rows_V_c_empty_n;
wire    img_1_cols_V_c_full_n;
wire   [10:0] img_1_cols_V_c_dout;
wire    img_1_cols_V_c_empty_n;
wire    img_1_data_stream_0_full_n;
wire   [7:0] img_1_data_stream_0_dout;
wire    img_1_data_stream_0_empty_n;
wire    img_1_rows_V_c4_full_n;
wire   [9:0] img_1_rows_V_c4_dout;
wire    img_1_rows_V_c4_empty_n;
wire    img_1_cols_V_c5_full_n;
wire   [10:0] img_1_cols_V_c5_dout;
wire    img_1_cols_V_c5_empty_n;
wire    Block_proc_U0_start_full_n;
wire    Block_proc_U0_start_write;
wire   [0:0] start_for_Mat2AXIvideo_DMA_U0_din;
wire    start_for_Mat2AXIvideo_DMA_U0_full_n;
wire   [0:0] start_for_Mat2AXIvideo_DMA_U0_dout;
wire    start_for_Mat2AXIvideo_DMA_U0_empty_n;
wire    Mat2AXIvideo_DMA_U0_start_full_n;
wire    Mat2AXIvideo_DMA_U0_start_write;

Block_proc Block_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_proc_U0_ap_start),
    .ap_done(Block_proc_U0_ap_done),
    .ap_continue(Block_proc_U0_ap_continue),
    .ap_idle(Block_proc_U0_ap_idle),
    .ap_ready(Block_proc_U0_ap_ready),
    .img_1_rows_V_out_din(Block_proc_U0_img_1_rows_V_out_din),
    .img_1_rows_V_out_full_n(img_1_rows_V_c_full_n),
    .img_1_rows_V_out_write(Block_proc_U0_img_1_rows_V_out_write),
    .img_1_cols_V_out_din(Block_proc_U0_img_1_cols_V_out_din),
    .img_1_cols_V_out_full_n(img_1_cols_V_c_full_n),
    .img_1_cols_V_out_write(Block_proc_U0_img_1_cols_V_out_write)
);

AXIvideo2Mat_DMA AXIvideo2Mat_DMA_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIvideo2Mat_DMA_U0_ap_start),
    .start_full_n(start_for_Mat2AXIvideo_DMA_U0_full_n),
    .ap_done(AXIvideo2Mat_DMA_U0_ap_done),
    .ap_continue(AXIvideo2Mat_DMA_U0_ap_continue),
    .ap_idle(AXIvideo2Mat_DMA_U0_ap_idle),
    .ap_ready(AXIvideo2Mat_DMA_U0_ap_ready),
    .start_out(AXIvideo2Mat_DMA_U0_start_out),
    .start_write(AXIvideo2Mat_DMA_U0_start_write),
    .video_in_TDATA(video_in_TDATA),
    .video_in_TVALID(video_in_TVALID),
    .video_in_TREADY(AXIvideo2Mat_DMA_U0_video_in_TREADY),
    .video_in_TKEEP(video_in_TKEEP),
    .video_in_TSTRB(video_in_TSTRB),
    .video_in_TUSER(video_in_TUSER),
    .video_in_TLAST(video_in_TLAST),
    .video_in_TID(video_in_TID),
    .video_in_TDEST(video_in_TDEST),
    .img_rows_V_dout(img_1_rows_V_c_dout),
    .img_rows_V_empty_n(img_1_rows_V_c_empty_n),
    .img_rows_V_read(AXIvideo2Mat_DMA_U0_img_rows_V_read),
    .img_cols_V_dout(img_1_cols_V_c_dout),
    .img_cols_V_empty_n(img_1_cols_V_c_empty_n),
    .img_cols_V_read(AXIvideo2Mat_DMA_U0_img_cols_V_read),
    .img_data_stream_V_din(AXIvideo2Mat_DMA_U0_img_data_stream_V_din),
    .img_data_stream_V_full_n(img_1_data_stream_0_full_n),
    .img_data_stream_V_write(AXIvideo2Mat_DMA_U0_img_data_stream_V_write),
    .img_rows_V_out_din(AXIvideo2Mat_DMA_U0_img_rows_V_out_din),
    .img_rows_V_out_full_n(img_1_rows_V_c4_full_n),
    .img_rows_V_out_write(AXIvideo2Mat_DMA_U0_img_rows_V_out_write),
    .img_cols_V_out_din(AXIvideo2Mat_DMA_U0_img_cols_V_out_din),
    .img_cols_V_out_full_n(img_1_cols_V_c5_full_n),
    .img_cols_V_out_write(AXIvideo2Mat_DMA_U0_img_cols_V_out_write)
);

Mat2AXIvideo_DMA Mat2AXIvideo_DMA_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Mat2AXIvideo_DMA_U0_ap_start),
    .ap_done(Mat2AXIvideo_DMA_U0_ap_done),
    .ap_continue(Mat2AXIvideo_DMA_U0_ap_continue),
    .ap_idle(Mat2AXIvideo_DMA_U0_ap_idle),
    .ap_ready(Mat2AXIvideo_DMA_U0_ap_ready),
    .img_rows_V_dout(img_1_rows_V_c4_dout),
    .img_rows_V_empty_n(img_1_rows_V_c4_empty_n),
    .img_rows_V_read(Mat2AXIvideo_DMA_U0_img_rows_V_read),
    .img_cols_V_dout(img_1_cols_V_c5_dout),
    .img_cols_V_empty_n(img_1_cols_V_c5_empty_n),
    .img_cols_V_read(Mat2AXIvideo_DMA_U0_img_cols_V_read),
    .img_data_stream_V_dout(img_1_data_stream_0_dout),
    .img_data_stream_V_empty_n(img_1_data_stream_0_empty_n),
    .img_data_stream_V_read(Mat2AXIvideo_DMA_U0_img_data_stream_V_read),
    .video_out_TDATA(Mat2AXIvideo_DMA_U0_video_out_TDATA),
    .video_out_TVALID(Mat2AXIvideo_DMA_U0_video_out_TVALID),
    .video_out_TREADY(video_out_TREADY),
    .video_out_TKEEP(Mat2AXIvideo_DMA_U0_video_out_TKEEP),
    .video_out_TSTRB(Mat2AXIvideo_DMA_U0_video_out_TSTRB),
    .video_out_TUSER(Mat2AXIvideo_DMA_U0_video_out_TUSER),
    .video_out_TLAST(Mat2AXIvideo_DMA_U0_video_out_TLAST),
    .video_out_TID(Mat2AXIvideo_DMA_U0_video_out_TID),
    .video_out_TDEST(Mat2AXIvideo_DMA_U0_video_out_TDEST)
);

fifo_w10_d2_A img_1_rows_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_img_1_rows_V_out_din),
    .if_full_n(img_1_rows_V_c_full_n),
    .if_write(Block_proc_U0_img_1_rows_V_out_write),
    .if_dout(img_1_rows_V_c_dout),
    .if_empty_n(img_1_rows_V_c_empty_n),
    .if_read(AXIvideo2Mat_DMA_U0_img_rows_V_read)
);

fifo_w11_d2_A img_1_cols_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_img_1_cols_V_out_din),
    .if_full_n(img_1_cols_V_c_full_n),
    .if_write(Block_proc_U0_img_1_cols_V_out_write),
    .if_dout(img_1_cols_V_c_dout),
    .if_empty_n(img_1_cols_V_c_empty_n),
    .if_read(AXIvideo2Mat_DMA_U0_img_cols_V_read)
);

fifo_w8_d2_A img_1_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_DMA_U0_img_data_stream_V_din),
    .if_full_n(img_1_data_stream_0_full_n),
    .if_write(AXIvideo2Mat_DMA_U0_img_data_stream_V_write),
    .if_dout(img_1_data_stream_0_dout),
    .if_empty_n(img_1_data_stream_0_empty_n),
    .if_read(Mat2AXIvideo_DMA_U0_img_data_stream_V_read)
);

fifo_w10_d2_A img_1_rows_V_c4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_DMA_U0_img_rows_V_out_din),
    .if_full_n(img_1_rows_V_c4_full_n),
    .if_write(AXIvideo2Mat_DMA_U0_img_rows_V_out_write),
    .if_dout(img_1_rows_V_c4_dout),
    .if_empty_n(img_1_rows_V_c4_empty_n),
    .if_read(Mat2AXIvideo_DMA_U0_img_rows_V_read)
);

fifo_w11_d2_A img_1_cols_V_c5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_DMA_U0_img_cols_V_out_din),
    .if_full_n(img_1_cols_V_c5_full_n),
    .if_write(AXIvideo2Mat_DMA_U0_img_cols_V_out_write),
    .if_dout(img_1_cols_V_c5_dout),
    .if_empty_n(img_1_cols_V_c5_empty_n),
    .if_read(Mat2AXIvideo_DMA_U0_img_cols_V_read)
);

start_for_Mat2AXIbkb start_for_Mat2AXIbkb_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Mat2AXIvideo_DMA_U0_din),
    .if_full_n(start_for_Mat2AXIvideo_DMA_U0_full_n),
    .if_write(AXIvideo2Mat_DMA_U0_start_write),
    .if_dout(start_for_Mat2AXIvideo_DMA_U0_dout),
    .if_empty_n(start_for_Mat2AXIvideo_DMA_U0_empty_n),
    .if_read(Mat2AXIvideo_DMA_U0_ap_ready)
);

assign AXIvideo2Mat_DMA_U0_ap_continue = 1'b1;

assign AXIvideo2Mat_DMA_U0_ap_start = 1'b1;

assign Block_proc_U0_ap_continue = 1'b1;

assign Block_proc_U0_ap_start = 1'b1;

assign Block_proc_U0_start_full_n = 1'b1;

assign Block_proc_U0_start_write = 1'b0;

assign Mat2AXIvideo_DMA_U0_ap_continue = 1'b1;

assign Mat2AXIvideo_DMA_U0_ap_start = start_for_Mat2AXIvideo_DMA_U0_empty_n;

assign Mat2AXIvideo_DMA_U0_start_full_n = 1'b1;

assign Mat2AXIvideo_DMA_U0_start_write = 1'b0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b0;

assign start_for_Mat2AXIvideo_DMA_U0_din = 1'b1;

assign video_in_TREADY = AXIvideo2Mat_DMA_U0_video_in_TREADY;

assign video_out_TDATA = Mat2AXIvideo_DMA_U0_video_out_TDATA;

assign video_out_TDEST = Mat2AXIvideo_DMA_U0_video_out_TDEST;

assign video_out_TID = Mat2AXIvideo_DMA_U0_video_out_TID;

assign video_out_TKEEP = Mat2AXIvideo_DMA_U0_video_out_TKEEP;

assign video_out_TLAST = Mat2AXIvideo_DMA_U0_video_out_TLAST;

assign video_out_TSTRB = Mat2AXIvideo_DMA_U0_video_out_TSTRB;

assign video_out_TUSER = Mat2AXIvideo_DMA_U0_video_out_TUSER;

assign video_out_TVALID = Mat2AXIvideo_DMA_U0_video_out_TVALID;

endmodule //passthrough
