// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "filter.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_lv<8> filter::ap_const_lv8_0 = "00000000";
const sc_lv<1> filter::ap_const_lv1_0 = "0";
const sc_logic filter::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic filter::ap_const_logic_0 = sc_dt::Log_0;

filter::filter(sc_module_name name) : sc_module(name), mVcdFile(0) {
    Block_proc_U0 = new Block_proc("Block_proc_U0");
    Block_proc_U0->ap_clk(ap_clk);
    Block_proc_U0->ap_rst(ap_rst_n_inv);
    Block_proc_U0->ap_start(Block_proc_U0_ap_start);
    Block_proc_U0->start_full_n(start_for_Threshold_U0_full_n);
    Block_proc_U0->ap_done(Block_proc_U0_ap_done);
    Block_proc_U0->ap_continue(Block_proc_U0_ap_continue);
    Block_proc_U0->ap_idle(Block_proc_U0_ap_idle);
    Block_proc_U0->ap_ready(Block_proc_U0_ap_ready);
    Block_proc_U0->start_out(Block_proc_U0_start_out);
    Block_proc_U0->start_write(Block_proc_U0_start_write);
    Block_proc_U0->img_1_rows_V_out_din(Block_proc_U0_img_1_rows_V_out_din);
    Block_proc_U0->img_1_rows_V_out_full_n(img_1_rows_V_c_full_n);
    Block_proc_U0->img_1_rows_V_out_write(Block_proc_U0_img_1_rows_V_out_write);
    Block_proc_U0->img_1_cols_V_out_din(Block_proc_U0_img_1_cols_V_out_din);
    Block_proc_U0->img_1_cols_V_out_full_n(img_1_cols_V_c_full_n);
    Block_proc_U0->img_1_cols_V_out_write(Block_proc_U0_img_1_cols_V_out_write);
    Block_proc_U0->img_3_rows_V_out_din(Block_proc_U0_img_3_rows_V_out_din);
    Block_proc_U0->img_3_rows_V_out_full_n(img_3_rows_V_c_full_n);
    Block_proc_U0->img_3_rows_V_out_write(Block_proc_U0_img_3_rows_V_out_write);
    Block_proc_U0->img_3_cols_V_out_din(Block_proc_U0_img_3_cols_V_out_din);
    Block_proc_U0->img_3_cols_V_out_full_n(img_3_cols_V_c_full_n);
    Block_proc_U0->img_3_cols_V_out_write(Block_proc_U0_img_3_cols_V_out_write);
    AXIvideo2Mat_U0 = new AXIvideo2Mat("AXIvideo2Mat_U0");
    AXIvideo2Mat_U0->ap_clk(ap_clk);
    AXIvideo2Mat_U0->ap_rst(ap_rst_n_inv);
    AXIvideo2Mat_U0->ap_start(AXIvideo2Mat_U0_ap_start);
    AXIvideo2Mat_U0->start_full_n(start_for_GaussianBlur_U0_full_n);
    AXIvideo2Mat_U0->ap_done(AXIvideo2Mat_U0_ap_done);
    AXIvideo2Mat_U0->ap_continue(AXIvideo2Mat_U0_ap_continue);
    AXIvideo2Mat_U0->ap_idle(AXIvideo2Mat_U0_ap_idle);
    AXIvideo2Mat_U0->ap_ready(AXIvideo2Mat_U0_ap_ready);
    AXIvideo2Mat_U0->start_out(AXIvideo2Mat_U0_start_out);
    AXIvideo2Mat_U0->start_write(AXIvideo2Mat_U0_start_write);
    AXIvideo2Mat_U0->video_in_TDATA(video_in_TDATA);
    AXIvideo2Mat_U0->video_in_TVALID(video_in_TVALID);
    AXIvideo2Mat_U0->video_in_TREADY(AXIvideo2Mat_U0_video_in_TREADY);
    AXIvideo2Mat_U0->video_in_TKEEP(video_in_TKEEP);
    AXIvideo2Mat_U0->video_in_TSTRB(video_in_TSTRB);
    AXIvideo2Mat_U0->video_in_TUSER(video_in_TUSER);
    AXIvideo2Mat_U0->video_in_TLAST(video_in_TLAST);
    AXIvideo2Mat_U0->video_in_TID(video_in_TID);
    AXIvideo2Mat_U0->video_in_TDEST(video_in_TDEST);
    AXIvideo2Mat_U0->img_rows_V_dout(img_1_rows_V_c_dout);
    AXIvideo2Mat_U0->img_rows_V_empty_n(img_1_rows_V_c_empty_n);
    AXIvideo2Mat_U0->img_rows_V_read(AXIvideo2Mat_U0_img_rows_V_read);
    AXIvideo2Mat_U0->img_cols_V_dout(img_1_cols_V_c_dout);
    AXIvideo2Mat_U0->img_cols_V_empty_n(img_1_cols_V_c_empty_n);
    AXIvideo2Mat_U0->img_cols_V_read(AXIvideo2Mat_U0_img_cols_V_read);
    AXIvideo2Mat_U0->img_data_stream_V_din(AXIvideo2Mat_U0_img_data_stream_V_din);
    AXIvideo2Mat_U0->img_data_stream_V_full_n(img_1_data_stream_0_full_n);
    AXIvideo2Mat_U0->img_data_stream_V_write(AXIvideo2Mat_U0_img_data_stream_V_write);
    AXIvideo2Mat_U0->img_rows_V_out_din(AXIvideo2Mat_U0_img_rows_V_out_din);
    AXIvideo2Mat_U0->img_rows_V_out_full_n(img_1_rows_V_c10_full_n);
    AXIvideo2Mat_U0->img_rows_V_out_write(AXIvideo2Mat_U0_img_rows_V_out_write);
    AXIvideo2Mat_U0->img_cols_V_out_din(AXIvideo2Mat_U0_img_cols_V_out_din);
    AXIvideo2Mat_U0->img_cols_V_out_full_n(img_1_cols_V_c11_full_n);
    AXIvideo2Mat_U0->img_cols_V_out_write(AXIvideo2Mat_U0_img_cols_V_out_write);
    GaussianBlur_U0 = new GaussianBlur("GaussianBlur_U0");
    GaussianBlur_U0->ap_clk(ap_clk);
    GaussianBlur_U0->ap_rst(ap_rst_n_inv);
    GaussianBlur_U0->ap_start(GaussianBlur_U0_ap_start);
    GaussianBlur_U0->ap_done(GaussianBlur_U0_ap_done);
    GaussianBlur_U0->ap_continue(GaussianBlur_U0_ap_continue);
    GaussianBlur_U0->ap_idle(GaussianBlur_U0_ap_idle);
    GaussianBlur_U0->ap_ready(GaussianBlur_U0_ap_ready);
    GaussianBlur_U0->p_src_rows_V_dout(img_1_rows_V_c10_dout);
    GaussianBlur_U0->p_src_rows_V_empty_n(img_1_rows_V_c10_empty_n);
    GaussianBlur_U0->p_src_rows_V_read(GaussianBlur_U0_p_src_rows_V_read);
    GaussianBlur_U0->p_src_cols_V_dout(img_1_cols_V_c11_dout);
    GaussianBlur_U0->p_src_cols_V_empty_n(img_1_cols_V_c11_empty_n);
    GaussianBlur_U0->p_src_cols_V_read(GaussianBlur_U0_p_src_cols_V_read);
    GaussianBlur_U0->p_src_data_stream_V_dout(img_1_data_stream_0_dout);
    GaussianBlur_U0->p_src_data_stream_V_empty_n(img_1_data_stream_0_empty_n);
    GaussianBlur_U0->p_src_data_stream_V_read(GaussianBlur_U0_p_src_data_stream_V_read);
    GaussianBlur_U0->p_dst_data_stream_V_din(GaussianBlur_U0_p_dst_data_stream_V_din);
    GaussianBlur_U0->p_dst_data_stream_V_full_n(img_2_data_stream_0_full_n);
    GaussianBlur_U0->p_dst_data_stream_V_write(GaussianBlur_U0_p_dst_data_stream_V_write);
    Threshold_U0 = new Threshold("Threshold_U0");
    Threshold_U0->ap_clk(ap_clk);
    Threshold_U0->ap_rst(ap_rst_n_inv);
    Threshold_U0->ap_start(Threshold_U0_ap_start);
    Threshold_U0->start_full_n(start_for_Mat2AXIvideo_U0_full_n);
    Threshold_U0->ap_done(Threshold_U0_ap_done);
    Threshold_U0->ap_continue(Threshold_U0_ap_continue);
    Threshold_U0->ap_idle(Threshold_U0_ap_idle);
    Threshold_U0->ap_ready(Threshold_U0_ap_ready);
    Threshold_U0->start_out(Threshold_U0_start_out);
    Threshold_U0->start_write(Threshold_U0_start_write);
    Threshold_U0->src_data_stream_V_dout(img_2_data_stream_0_dout);
    Threshold_U0->src_data_stream_V_empty_n(img_2_data_stream_0_empty_n);
    Threshold_U0->src_data_stream_V_read(Threshold_U0_src_data_stream_V_read);
    Threshold_U0->dst_rows_V_dout(img_3_rows_V_c_dout);
    Threshold_U0->dst_rows_V_empty_n(img_3_rows_V_c_empty_n);
    Threshold_U0->dst_rows_V_read(Threshold_U0_dst_rows_V_read);
    Threshold_U0->dst_cols_V_dout(img_3_cols_V_c_dout);
    Threshold_U0->dst_cols_V_empty_n(img_3_cols_V_c_empty_n);
    Threshold_U0->dst_cols_V_read(Threshold_U0_dst_cols_V_read);
    Threshold_U0->dst_data_stream_V_din(Threshold_U0_dst_data_stream_V_din);
    Threshold_U0->dst_data_stream_V_full_n(img_3_data_stream_0_full_n);
    Threshold_U0->dst_data_stream_V_write(Threshold_U0_dst_data_stream_V_write);
    Threshold_U0->dst_rows_V_out_din(Threshold_U0_dst_rows_V_out_din);
    Threshold_U0->dst_rows_V_out_full_n(img_3_rows_V_c12_full_n);
    Threshold_U0->dst_rows_V_out_write(Threshold_U0_dst_rows_V_out_write);
    Threshold_U0->dst_cols_V_out_din(Threshold_U0_dst_cols_V_out_din);
    Threshold_U0->dst_cols_V_out_full_n(img_3_cols_V_c13_full_n);
    Threshold_U0->dst_cols_V_out_write(Threshold_U0_dst_cols_V_out_write);
    Mat2AXIvideo_U0 = new Mat2AXIvideo("Mat2AXIvideo_U0");
    Mat2AXIvideo_U0->ap_clk(ap_clk);
    Mat2AXIvideo_U0->ap_rst(ap_rst_n_inv);
    Mat2AXIvideo_U0->ap_start(Mat2AXIvideo_U0_ap_start);
    Mat2AXIvideo_U0->ap_done(Mat2AXIvideo_U0_ap_done);
    Mat2AXIvideo_U0->ap_continue(Mat2AXIvideo_U0_ap_continue);
    Mat2AXIvideo_U0->ap_idle(Mat2AXIvideo_U0_ap_idle);
    Mat2AXIvideo_U0->ap_ready(Mat2AXIvideo_U0_ap_ready);
    Mat2AXIvideo_U0->img_rows_V_dout(img_3_rows_V_c12_dout);
    Mat2AXIvideo_U0->img_rows_V_empty_n(img_3_rows_V_c12_empty_n);
    Mat2AXIvideo_U0->img_rows_V_read(Mat2AXIvideo_U0_img_rows_V_read);
    Mat2AXIvideo_U0->img_cols_V_dout(img_3_cols_V_c13_dout);
    Mat2AXIvideo_U0->img_cols_V_empty_n(img_3_cols_V_c13_empty_n);
    Mat2AXIvideo_U0->img_cols_V_read(Mat2AXIvideo_U0_img_cols_V_read);
    Mat2AXIvideo_U0->img_data_stream_V_dout(img_3_data_stream_0_dout);
    Mat2AXIvideo_U0->img_data_stream_V_empty_n(img_3_data_stream_0_empty_n);
    Mat2AXIvideo_U0->img_data_stream_V_read(Mat2AXIvideo_U0_img_data_stream_V_read);
    Mat2AXIvideo_U0->video_out_TDATA(Mat2AXIvideo_U0_video_out_TDATA);
    Mat2AXIvideo_U0->video_out_TVALID(Mat2AXIvideo_U0_video_out_TVALID);
    Mat2AXIvideo_U0->video_out_TREADY(video_out_TREADY);
    Mat2AXIvideo_U0->video_out_TKEEP(Mat2AXIvideo_U0_video_out_TKEEP);
    Mat2AXIvideo_U0->video_out_TSTRB(Mat2AXIvideo_U0_video_out_TSTRB);
    Mat2AXIvideo_U0->video_out_TUSER(Mat2AXIvideo_U0_video_out_TUSER);
    Mat2AXIvideo_U0->video_out_TLAST(Mat2AXIvideo_U0_video_out_TLAST);
    Mat2AXIvideo_U0->video_out_TID(Mat2AXIvideo_U0_video_out_TID);
    Mat2AXIvideo_U0->video_out_TDEST(Mat2AXIvideo_U0_video_out_TDEST);
    img_1_rows_V_c_U = new fifo_w10_d2_A("img_1_rows_V_c_U");
    img_1_rows_V_c_U->clk(ap_clk);
    img_1_rows_V_c_U->reset(ap_rst_n_inv);
    img_1_rows_V_c_U->if_read_ce(ap_var_for_const0);
    img_1_rows_V_c_U->if_write_ce(ap_var_for_const0);
    img_1_rows_V_c_U->if_din(Block_proc_U0_img_1_rows_V_out_din);
    img_1_rows_V_c_U->if_full_n(img_1_rows_V_c_full_n);
    img_1_rows_V_c_U->if_write(Block_proc_U0_img_1_rows_V_out_write);
    img_1_rows_V_c_U->if_dout(img_1_rows_V_c_dout);
    img_1_rows_V_c_U->if_empty_n(img_1_rows_V_c_empty_n);
    img_1_rows_V_c_U->if_read(AXIvideo2Mat_U0_img_rows_V_read);
    img_1_cols_V_c_U = new fifo_w11_d2_A("img_1_cols_V_c_U");
    img_1_cols_V_c_U->clk(ap_clk);
    img_1_cols_V_c_U->reset(ap_rst_n_inv);
    img_1_cols_V_c_U->if_read_ce(ap_var_for_const0);
    img_1_cols_V_c_U->if_write_ce(ap_var_for_const0);
    img_1_cols_V_c_U->if_din(Block_proc_U0_img_1_cols_V_out_din);
    img_1_cols_V_c_U->if_full_n(img_1_cols_V_c_full_n);
    img_1_cols_V_c_U->if_write(Block_proc_U0_img_1_cols_V_out_write);
    img_1_cols_V_c_U->if_dout(img_1_cols_V_c_dout);
    img_1_cols_V_c_U->if_empty_n(img_1_cols_V_c_empty_n);
    img_1_cols_V_c_U->if_read(AXIvideo2Mat_U0_img_cols_V_read);
    img_3_rows_V_c_U = new fifo_w10_d4_A("img_3_rows_V_c_U");
    img_3_rows_V_c_U->clk(ap_clk);
    img_3_rows_V_c_U->reset(ap_rst_n_inv);
    img_3_rows_V_c_U->if_read_ce(ap_var_for_const0);
    img_3_rows_V_c_U->if_write_ce(ap_var_for_const0);
    img_3_rows_V_c_U->if_din(Block_proc_U0_img_3_rows_V_out_din);
    img_3_rows_V_c_U->if_full_n(img_3_rows_V_c_full_n);
    img_3_rows_V_c_U->if_write(Block_proc_U0_img_3_rows_V_out_write);
    img_3_rows_V_c_U->if_dout(img_3_rows_V_c_dout);
    img_3_rows_V_c_U->if_empty_n(img_3_rows_V_c_empty_n);
    img_3_rows_V_c_U->if_read(Threshold_U0_dst_rows_V_read);
    img_3_cols_V_c_U = new fifo_w11_d4_A("img_3_cols_V_c_U");
    img_3_cols_V_c_U->clk(ap_clk);
    img_3_cols_V_c_U->reset(ap_rst_n_inv);
    img_3_cols_V_c_U->if_read_ce(ap_var_for_const0);
    img_3_cols_V_c_U->if_write_ce(ap_var_for_const0);
    img_3_cols_V_c_U->if_din(Block_proc_U0_img_3_cols_V_out_din);
    img_3_cols_V_c_U->if_full_n(img_3_cols_V_c_full_n);
    img_3_cols_V_c_U->if_write(Block_proc_U0_img_3_cols_V_out_write);
    img_3_cols_V_c_U->if_dout(img_3_cols_V_c_dout);
    img_3_cols_V_c_U->if_empty_n(img_3_cols_V_c_empty_n);
    img_3_cols_V_c_U->if_read(Threshold_U0_dst_cols_V_read);
    img_1_data_stream_0_U = new fifo_w8_d2_A("img_1_data_stream_0_U");
    img_1_data_stream_0_U->clk(ap_clk);
    img_1_data_stream_0_U->reset(ap_rst_n_inv);
    img_1_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_1_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_1_data_stream_0_U->if_din(AXIvideo2Mat_U0_img_data_stream_V_din);
    img_1_data_stream_0_U->if_full_n(img_1_data_stream_0_full_n);
    img_1_data_stream_0_U->if_write(AXIvideo2Mat_U0_img_data_stream_V_write);
    img_1_data_stream_0_U->if_dout(img_1_data_stream_0_dout);
    img_1_data_stream_0_U->if_empty_n(img_1_data_stream_0_empty_n);
    img_1_data_stream_0_U->if_read(GaussianBlur_U0_p_src_data_stream_V_read);
    img_1_rows_V_c10_U = new fifo_w10_d2_A("img_1_rows_V_c10_U");
    img_1_rows_V_c10_U->clk(ap_clk);
    img_1_rows_V_c10_U->reset(ap_rst_n_inv);
    img_1_rows_V_c10_U->if_read_ce(ap_var_for_const0);
    img_1_rows_V_c10_U->if_write_ce(ap_var_for_const0);
    img_1_rows_V_c10_U->if_din(AXIvideo2Mat_U0_img_rows_V_out_din);
    img_1_rows_V_c10_U->if_full_n(img_1_rows_V_c10_full_n);
    img_1_rows_V_c10_U->if_write(AXIvideo2Mat_U0_img_rows_V_out_write);
    img_1_rows_V_c10_U->if_dout(img_1_rows_V_c10_dout);
    img_1_rows_V_c10_U->if_empty_n(img_1_rows_V_c10_empty_n);
    img_1_rows_V_c10_U->if_read(GaussianBlur_U0_p_src_rows_V_read);
    img_1_cols_V_c11_U = new fifo_w11_d2_A("img_1_cols_V_c11_U");
    img_1_cols_V_c11_U->clk(ap_clk);
    img_1_cols_V_c11_U->reset(ap_rst_n_inv);
    img_1_cols_V_c11_U->if_read_ce(ap_var_for_const0);
    img_1_cols_V_c11_U->if_write_ce(ap_var_for_const0);
    img_1_cols_V_c11_U->if_din(AXIvideo2Mat_U0_img_cols_V_out_din);
    img_1_cols_V_c11_U->if_full_n(img_1_cols_V_c11_full_n);
    img_1_cols_V_c11_U->if_write(AXIvideo2Mat_U0_img_cols_V_out_write);
    img_1_cols_V_c11_U->if_dout(img_1_cols_V_c11_dout);
    img_1_cols_V_c11_U->if_empty_n(img_1_cols_V_c11_empty_n);
    img_1_cols_V_c11_U->if_read(GaussianBlur_U0_p_src_cols_V_read);
    img_2_data_stream_0_U = new fifo_w8_d2_A("img_2_data_stream_0_U");
    img_2_data_stream_0_U->clk(ap_clk);
    img_2_data_stream_0_U->reset(ap_rst_n_inv);
    img_2_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_2_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_2_data_stream_0_U->if_din(GaussianBlur_U0_p_dst_data_stream_V_din);
    img_2_data_stream_0_U->if_full_n(img_2_data_stream_0_full_n);
    img_2_data_stream_0_U->if_write(GaussianBlur_U0_p_dst_data_stream_V_write);
    img_2_data_stream_0_U->if_dout(img_2_data_stream_0_dout);
    img_2_data_stream_0_U->if_empty_n(img_2_data_stream_0_empty_n);
    img_2_data_stream_0_U->if_read(Threshold_U0_src_data_stream_V_read);
    img_3_data_stream_0_U = new fifo_w8_d2_A("img_3_data_stream_0_U");
    img_3_data_stream_0_U->clk(ap_clk);
    img_3_data_stream_0_U->reset(ap_rst_n_inv);
    img_3_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_3_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_3_data_stream_0_U->if_din(Threshold_U0_dst_data_stream_V_din);
    img_3_data_stream_0_U->if_full_n(img_3_data_stream_0_full_n);
    img_3_data_stream_0_U->if_write(Threshold_U0_dst_data_stream_V_write);
    img_3_data_stream_0_U->if_dout(img_3_data_stream_0_dout);
    img_3_data_stream_0_U->if_empty_n(img_3_data_stream_0_empty_n);
    img_3_data_stream_0_U->if_read(Mat2AXIvideo_U0_img_data_stream_V_read);
    img_3_rows_V_c12_U = new fifo_w10_d2_A("img_3_rows_V_c12_U");
    img_3_rows_V_c12_U->clk(ap_clk);
    img_3_rows_V_c12_U->reset(ap_rst_n_inv);
    img_3_rows_V_c12_U->if_read_ce(ap_var_for_const0);
    img_3_rows_V_c12_U->if_write_ce(ap_var_for_const0);
    img_3_rows_V_c12_U->if_din(Threshold_U0_dst_rows_V_out_din);
    img_3_rows_V_c12_U->if_full_n(img_3_rows_V_c12_full_n);
    img_3_rows_V_c12_U->if_write(Threshold_U0_dst_rows_V_out_write);
    img_3_rows_V_c12_U->if_dout(img_3_rows_V_c12_dout);
    img_3_rows_V_c12_U->if_empty_n(img_3_rows_V_c12_empty_n);
    img_3_rows_V_c12_U->if_read(Mat2AXIvideo_U0_img_rows_V_read);
    img_3_cols_V_c13_U = new fifo_w11_d2_A("img_3_cols_V_c13_U");
    img_3_cols_V_c13_U->clk(ap_clk);
    img_3_cols_V_c13_U->reset(ap_rst_n_inv);
    img_3_cols_V_c13_U->if_read_ce(ap_var_for_const0);
    img_3_cols_V_c13_U->if_write_ce(ap_var_for_const0);
    img_3_cols_V_c13_U->if_din(Threshold_U0_dst_cols_V_out_din);
    img_3_cols_V_c13_U->if_full_n(img_3_cols_V_c13_full_n);
    img_3_cols_V_c13_U->if_write(Threshold_U0_dst_cols_V_out_write);
    img_3_cols_V_c13_U->if_dout(img_3_cols_V_c13_dout);
    img_3_cols_V_c13_U->if_empty_n(img_3_cols_V_c13_empty_n);
    img_3_cols_V_c13_U->if_read(Mat2AXIvideo_U0_img_cols_V_read);
    start_for_Threshovdy_U = new start_for_Threshovdy("start_for_Threshovdy_U");
    start_for_Threshovdy_U->clk(ap_clk);
    start_for_Threshovdy_U->reset(ap_rst_n_inv);
    start_for_Threshovdy_U->if_read_ce(ap_var_for_const0);
    start_for_Threshovdy_U->if_write_ce(ap_var_for_const0);
    start_for_Threshovdy_U->if_din(start_for_Threshold_U0_din);
    start_for_Threshovdy_U->if_full_n(start_for_Threshold_U0_full_n);
    start_for_Threshovdy_U->if_write(Block_proc_U0_start_write);
    start_for_Threshovdy_U->if_dout(start_for_Threshold_U0_dout);
    start_for_Threshovdy_U->if_empty_n(start_for_Threshold_U0_empty_n);
    start_for_Threshovdy_U->if_read(Threshold_U0_ap_ready);
    start_for_GaussiawdI_U = new start_for_GaussiawdI("start_for_GaussiawdI_U");
    start_for_GaussiawdI_U->clk(ap_clk);
    start_for_GaussiawdI_U->reset(ap_rst_n_inv);
    start_for_GaussiawdI_U->if_read_ce(ap_var_for_const0);
    start_for_GaussiawdI_U->if_write_ce(ap_var_for_const0);
    start_for_GaussiawdI_U->if_din(start_for_GaussianBlur_U0_din);
    start_for_GaussiawdI_U->if_full_n(start_for_GaussianBlur_U0_full_n);
    start_for_GaussiawdI_U->if_write(AXIvideo2Mat_U0_start_write);
    start_for_GaussiawdI_U->if_dout(start_for_GaussianBlur_U0_dout);
    start_for_GaussiawdI_U->if_empty_n(start_for_GaussianBlur_U0_empty_n);
    start_for_GaussiawdI_U->if_read(GaussianBlur_U0_ap_ready);
    start_for_Mat2AXIxdS_U = new start_for_Mat2AXIxdS("start_for_Mat2AXIxdS_U");
    start_for_Mat2AXIxdS_U->clk(ap_clk);
    start_for_Mat2AXIxdS_U->reset(ap_rst_n_inv);
    start_for_Mat2AXIxdS_U->if_read_ce(ap_var_for_const0);
    start_for_Mat2AXIxdS_U->if_write_ce(ap_var_for_const0);
    start_for_Mat2AXIxdS_U->if_din(start_for_Mat2AXIvideo_U0_din);
    start_for_Mat2AXIxdS_U->if_full_n(start_for_Mat2AXIvideo_U0_full_n);
    start_for_Mat2AXIxdS_U->if_write(Threshold_U0_start_write);
    start_for_Mat2AXIxdS_U->if_dout(start_for_Mat2AXIvideo_U0_dout);
    start_for_Mat2AXIxdS_U->if_empty_n(start_for_Mat2AXIvideo_U0_empty_n);
    start_for_Mat2AXIxdS_U->if_read(Mat2AXIvideo_U0_ap_ready);

    SC_METHOD(thread_AXIvideo2Mat_U0_ap_continue);

    SC_METHOD(thread_AXIvideo2Mat_U0_ap_start);

    SC_METHOD(thread_Block_proc_U0_ap_continue);

    SC_METHOD(thread_Block_proc_U0_ap_start);

    SC_METHOD(thread_GaussianBlur_U0_ap_continue);

    SC_METHOD(thread_GaussianBlur_U0_ap_start);
    sensitive << ( start_for_GaussianBlur_U0_empty_n );

    SC_METHOD(thread_GaussianBlur_U0_start_full_n);

    SC_METHOD(thread_GaussianBlur_U0_start_write);

    SC_METHOD(thread_Mat2AXIvideo_U0_ap_continue);

    SC_METHOD(thread_Mat2AXIvideo_U0_ap_start);
    sensitive << ( start_for_Mat2AXIvideo_U0_empty_n );

    SC_METHOD(thread_Mat2AXIvideo_U0_start_full_n);

    SC_METHOD(thread_Mat2AXIvideo_U0_start_write);

    SC_METHOD(thread_Threshold_U0_ap_continue);

    SC_METHOD(thread_Threshold_U0_ap_start);
    sensitive << ( start_for_Threshold_U0_empty_n );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_start_for_GaussianBlur_U0_din);

    SC_METHOD(thread_start_for_Mat2AXIvideo_U0_din);

    SC_METHOD(thread_start_for_Threshold_U0_din);

    SC_METHOD(thread_video_in_TREADY);
    sensitive << ( AXIvideo2Mat_U0_video_in_TREADY );

    SC_METHOD(thread_video_out_TDATA);
    sensitive << ( Mat2AXIvideo_U0_video_out_TDATA );

    SC_METHOD(thread_video_out_TDEST);
    sensitive << ( Mat2AXIvideo_U0_video_out_TDEST );

    SC_METHOD(thread_video_out_TID);
    sensitive << ( Mat2AXIvideo_U0_video_out_TID );

    SC_METHOD(thread_video_out_TKEEP);
    sensitive << ( Mat2AXIvideo_U0_video_out_TKEEP );

    SC_METHOD(thread_video_out_TLAST);
    sensitive << ( Mat2AXIvideo_U0_video_out_TLAST );

    SC_METHOD(thread_video_out_TSTRB);
    sensitive << ( Mat2AXIvideo_U0_video_out_TSTRB );

    SC_METHOD(thread_video_out_TUSER);
    sensitive << ( Mat2AXIvideo_U0_video_out_TUSER );

    SC_METHOD(thread_video_out_TVALID);
    sensitive << ( Mat2AXIvideo_U0_video_out_TVALID );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "filter_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, video_in_TDATA, "(port)video_in_TDATA");
    sc_trace(mVcdFile, video_in_TKEEP, "(port)video_in_TKEEP");
    sc_trace(mVcdFile, video_in_TSTRB, "(port)video_in_TSTRB");
    sc_trace(mVcdFile, video_in_TUSER, "(port)video_in_TUSER");
    sc_trace(mVcdFile, video_in_TLAST, "(port)video_in_TLAST");
    sc_trace(mVcdFile, video_in_TID, "(port)video_in_TID");
    sc_trace(mVcdFile, video_in_TDEST, "(port)video_in_TDEST");
    sc_trace(mVcdFile, video_out_TDATA, "(port)video_out_TDATA");
    sc_trace(mVcdFile, video_out_TKEEP, "(port)video_out_TKEEP");
    sc_trace(mVcdFile, video_out_TSTRB, "(port)video_out_TSTRB");
    sc_trace(mVcdFile, video_out_TUSER, "(port)video_out_TUSER");
    sc_trace(mVcdFile, video_out_TLAST, "(port)video_out_TLAST");
    sc_trace(mVcdFile, video_out_TID, "(port)video_out_TID");
    sc_trace(mVcdFile, video_out_TDEST, "(port)video_out_TDEST");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, video_in_TVALID, "(port)video_in_TVALID");
    sc_trace(mVcdFile, video_in_TREADY, "(port)video_in_TREADY");
    sc_trace(mVcdFile, video_out_TVALID, "(port)video_out_TVALID");
    sc_trace(mVcdFile, video_out_TREADY, "(port)video_out_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, Block_proc_U0_ap_start, "Block_proc_U0_ap_start");
    sc_trace(mVcdFile, Block_proc_U0_ap_done, "Block_proc_U0_ap_done");
    sc_trace(mVcdFile, Block_proc_U0_ap_continue, "Block_proc_U0_ap_continue");
    sc_trace(mVcdFile, Block_proc_U0_ap_idle, "Block_proc_U0_ap_idle");
    sc_trace(mVcdFile, Block_proc_U0_ap_ready, "Block_proc_U0_ap_ready");
    sc_trace(mVcdFile, Block_proc_U0_start_out, "Block_proc_U0_start_out");
    sc_trace(mVcdFile, Block_proc_U0_start_write, "Block_proc_U0_start_write");
    sc_trace(mVcdFile, Block_proc_U0_img_1_rows_V_out_din, "Block_proc_U0_img_1_rows_V_out_din");
    sc_trace(mVcdFile, Block_proc_U0_img_1_rows_V_out_write, "Block_proc_U0_img_1_rows_V_out_write");
    sc_trace(mVcdFile, Block_proc_U0_img_1_cols_V_out_din, "Block_proc_U0_img_1_cols_V_out_din");
    sc_trace(mVcdFile, Block_proc_U0_img_1_cols_V_out_write, "Block_proc_U0_img_1_cols_V_out_write");
    sc_trace(mVcdFile, Block_proc_U0_img_3_rows_V_out_din, "Block_proc_U0_img_3_rows_V_out_din");
    sc_trace(mVcdFile, Block_proc_U0_img_3_rows_V_out_write, "Block_proc_U0_img_3_rows_V_out_write");
    sc_trace(mVcdFile, Block_proc_U0_img_3_cols_V_out_din, "Block_proc_U0_img_3_cols_V_out_din");
    sc_trace(mVcdFile, Block_proc_U0_img_3_cols_V_out_write, "Block_proc_U0_img_3_cols_V_out_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_start, "AXIvideo2Mat_U0_ap_start");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_done, "AXIvideo2Mat_U0_ap_done");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_continue, "AXIvideo2Mat_U0_ap_continue");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_idle, "AXIvideo2Mat_U0_ap_idle");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_ready, "AXIvideo2Mat_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_start_out, "AXIvideo2Mat_U0_start_out");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_start_write, "AXIvideo2Mat_U0_start_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_video_in_TREADY, "AXIvideo2Mat_U0_video_in_TREADY");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_read, "AXIvideo2Mat_U0_img_rows_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_read, "AXIvideo2Mat_U0_img_cols_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_V_din, "AXIvideo2Mat_U0_img_data_stream_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_V_write, "AXIvideo2Mat_U0_img_data_stream_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_out_din, "AXIvideo2Mat_U0_img_rows_V_out_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_out_write, "AXIvideo2Mat_U0_img_rows_V_out_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_out_din, "AXIvideo2Mat_U0_img_cols_V_out_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_out_write, "AXIvideo2Mat_U0_img_cols_V_out_write");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_start, "GaussianBlur_U0_ap_start");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_done, "GaussianBlur_U0_ap_done");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_continue, "GaussianBlur_U0_ap_continue");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_idle, "GaussianBlur_U0_ap_idle");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_ready, "GaussianBlur_U0_ap_ready");
    sc_trace(mVcdFile, GaussianBlur_U0_p_src_rows_V_read, "GaussianBlur_U0_p_src_rows_V_read");
    sc_trace(mVcdFile, GaussianBlur_U0_p_src_cols_V_read, "GaussianBlur_U0_p_src_cols_V_read");
    sc_trace(mVcdFile, GaussianBlur_U0_p_src_data_stream_V_read, "GaussianBlur_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, GaussianBlur_U0_p_dst_data_stream_V_din, "GaussianBlur_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, GaussianBlur_U0_p_dst_data_stream_V_write, "GaussianBlur_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, Threshold_U0_ap_start, "Threshold_U0_ap_start");
    sc_trace(mVcdFile, Threshold_U0_ap_done, "Threshold_U0_ap_done");
    sc_trace(mVcdFile, Threshold_U0_ap_continue, "Threshold_U0_ap_continue");
    sc_trace(mVcdFile, Threshold_U0_ap_idle, "Threshold_U0_ap_idle");
    sc_trace(mVcdFile, Threshold_U0_ap_ready, "Threshold_U0_ap_ready");
    sc_trace(mVcdFile, Threshold_U0_start_out, "Threshold_U0_start_out");
    sc_trace(mVcdFile, Threshold_U0_start_write, "Threshold_U0_start_write");
    sc_trace(mVcdFile, Threshold_U0_src_data_stream_V_read, "Threshold_U0_src_data_stream_V_read");
    sc_trace(mVcdFile, Threshold_U0_dst_rows_V_read, "Threshold_U0_dst_rows_V_read");
    sc_trace(mVcdFile, Threshold_U0_dst_cols_V_read, "Threshold_U0_dst_cols_V_read");
    sc_trace(mVcdFile, Threshold_U0_dst_data_stream_V_din, "Threshold_U0_dst_data_stream_V_din");
    sc_trace(mVcdFile, Threshold_U0_dst_data_stream_V_write, "Threshold_U0_dst_data_stream_V_write");
    sc_trace(mVcdFile, Threshold_U0_dst_rows_V_out_din, "Threshold_U0_dst_rows_V_out_din");
    sc_trace(mVcdFile, Threshold_U0_dst_rows_V_out_write, "Threshold_U0_dst_rows_V_out_write");
    sc_trace(mVcdFile, Threshold_U0_dst_cols_V_out_din, "Threshold_U0_dst_cols_V_out_din");
    sc_trace(mVcdFile, Threshold_U0_dst_cols_V_out_write, "Threshold_U0_dst_cols_V_out_write");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_start, "Mat2AXIvideo_U0_ap_start");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_done, "Mat2AXIvideo_U0_ap_done");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_continue, "Mat2AXIvideo_U0_ap_continue");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_idle, "Mat2AXIvideo_U0_ap_idle");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_ready, "Mat2AXIvideo_U0_ap_ready");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_rows_V_read, "Mat2AXIvideo_U0_img_rows_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_cols_V_read, "Mat2AXIvideo_U0_img_cols_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_V_read, "Mat2AXIvideo_U0_img_data_stream_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_video_out_TDATA, "Mat2AXIvideo_U0_video_out_TDATA");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_video_out_TVALID, "Mat2AXIvideo_U0_video_out_TVALID");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_video_out_TKEEP, "Mat2AXIvideo_U0_video_out_TKEEP");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_video_out_TSTRB, "Mat2AXIvideo_U0_video_out_TSTRB");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_video_out_TUSER, "Mat2AXIvideo_U0_video_out_TUSER");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_video_out_TLAST, "Mat2AXIvideo_U0_video_out_TLAST");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_video_out_TID, "Mat2AXIvideo_U0_video_out_TID");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_video_out_TDEST, "Mat2AXIvideo_U0_video_out_TDEST");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, img_1_rows_V_c_full_n, "img_1_rows_V_c_full_n");
    sc_trace(mVcdFile, img_1_rows_V_c_dout, "img_1_rows_V_c_dout");
    sc_trace(mVcdFile, img_1_rows_V_c_empty_n, "img_1_rows_V_c_empty_n");
    sc_trace(mVcdFile, img_1_cols_V_c_full_n, "img_1_cols_V_c_full_n");
    sc_trace(mVcdFile, img_1_cols_V_c_dout, "img_1_cols_V_c_dout");
    sc_trace(mVcdFile, img_1_cols_V_c_empty_n, "img_1_cols_V_c_empty_n");
    sc_trace(mVcdFile, img_3_rows_V_c_full_n, "img_3_rows_V_c_full_n");
    sc_trace(mVcdFile, img_3_rows_V_c_dout, "img_3_rows_V_c_dout");
    sc_trace(mVcdFile, img_3_rows_V_c_empty_n, "img_3_rows_V_c_empty_n");
    sc_trace(mVcdFile, img_3_cols_V_c_full_n, "img_3_cols_V_c_full_n");
    sc_trace(mVcdFile, img_3_cols_V_c_dout, "img_3_cols_V_c_dout");
    sc_trace(mVcdFile, img_3_cols_V_c_empty_n, "img_3_cols_V_c_empty_n");
    sc_trace(mVcdFile, img_1_data_stream_0_full_n, "img_1_data_stream_0_full_n");
    sc_trace(mVcdFile, img_1_data_stream_0_dout, "img_1_data_stream_0_dout");
    sc_trace(mVcdFile, img_1_data_stream_0_empty_n, "img_1_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_1_rows_V_c10_full_n, "img_1_rows_V_c10_full_n");
    sc_trace(mVcdFile, img_1_rows_V_c10_dout, "img_1_rows_V_c10_dout");
    sc_trace(mVcdFile, img_1_rows_V_c10_empty_n, "img_1_rows_V_c10_empty_n");
    sc_trace(mVcdFile, img_1_cols_V_c11_full_n, "img_1_cols_V_c11_full_n");
    sc_trace(mVcdFile, img_1_cols_V_c11_dout, "img_1_cols_V_c11_dout");
    sc_trace(mVcdFile, img_1_cols_V_c11_empty_n, "img_1_cols_V_c11_empty_n");
    sc_trace(mVcdFile, img_2_data_stream_0_full_n, "img_2_data_stream_0_full_n");
    sc_trace(mVcdFile, img_2_data_stream_0_dout, "img_2_data_stream_0_dout");
    sc_trace(mVcdFile, img_2_data_stream_0_empty_n, "img_2_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_3_data_stream_0_full_n, "img_3_data_stream_0_full_n");
    sc_trace(mVcdFile, img_3_data_stream_0_dout, "img_3_data_stream_0_dout");
    sc_trace(mVcdFile, img_3_data_stream_0_empty_n, "img_3_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_3_rows_V_c12_full_n, "img_3_rows_V_c12_full_n");
    sc_trace(mVcdFile, img_3_rows_V_c12_dout, "img_3_rows_V_c12_dout");
    sc_trace(mVcdFile, img_3_rows_V_c12_empty_n, "img_3_rows_V_c12_empty_n");
    sc_trace(mVcdFile, img_3_cols_V_c13_full_n, "img_3_cols_V_c13_full_n");
    sc_trace(mVcdFile, img_3_cols_V_c13_dout, "img_3_cols_V_c13_dout");
    sc_trace(mVcdFile, img_3_cols_V_c13_empty_n, "img_3_cols_V_c13_empty_n");
    sc_trace(mVcdFile, start_for_Threshold_U0_din, "start_for_Threshold_U0_din");
    sc_trace(mVcdFile, start_for_Threshold_U0_full_n, "start_for_Threshold_U0_full_n");
    sc_trace(mVcdFile, start_for_Threshold_U0_dout, "start_for_Threshold_U0_dout");
    sc_trace(mVcdFile, start_for_Threshold_U0_empty_n, "start_for_Threshold_U0_empty_n");
    sc_trace(mVcdFile, start_for_GaussianBlur_U0_din, "start_for_GaussianBlur_U0_din");
    sc_trace(mVcdFile, start_for_GaussianBlur_U0_full_n, "start_for_GaussianBlur_U0_full_n");
    sc_trace(mVcdFile, start_for_GaussianBlur_U0_dout, "start_for_GaussianBlur_U0_dout");
    sc_trace(mVcdFile, start_for_GaussianBlur_U0_empty_n, "start_for_GaussianBlur_U0_empty_n");
    sc_trace(mVcdFile, GaussianBlur_U0_start_full_n, "GaussianBlur_U0_start_full_n");
    sc_trace(mVcdFile, GaussianBlur_U0_start_write, "GaussianBlur_U0_start_write");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_din, "start_for_Mat2AXIvideo_U0_din");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_full_n, "start_for_Mat2AXIvideo_U0_full_n");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_dout, "start_for_Mat2AXIvideo_U0_dout");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_empty_n, "start_for_Mat2AXIvideo_U0_empty_n");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_start_full_n, "Mat2AXIvideo_U0_start_full_n");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_start_write, "Mat2AXIvideo_U0_start_write");
#endif

    }
    mHdltvinHandle.open("filter.hdltvin.dat");
    mHdltvoutHandle.open("filter.hdltvout.dat");
}

filter::~filter() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete Block_proc_U0;
    delete AXIvideo2Mat_U0;
    delete GaussianBlur_U0;
    delete Threshold_U0;
    delete Mat2AXIvideo_U0;
    delete img_1_rows_V_c_U;
    delete img_1_cols_V_c_U;
    delete img_3_rows_V_c_U;
    delete img_3_cols_V_c_U;
    delete img_1_data_stream_0_U;
    delete img_1_rows_V_c10_U;
    delete img_1_cols_V_c11_U;
    delete img_2_data_stream_0_U;
    delete img_3_data_stream_0_U;
    delete img_3_rows_V_c12_U;
    delete img_3_cols_V_c13_U;
    delete start_for_Threshovdy_U;
    delete start_for_GaussiawdI_U;
    delete start_for_Mat2AXIxdS_U;
}

void filter::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void filter::thread_AXIvideo2Mat_U0_ap_continue() {
    AXIvideo2Mat_U0_ap_continue = ap_const_logic_1;
}

void filter::thread_AXIvideo2Mat_U0_ap_start() {
    AXIvideo2Mat_U0_ap_start = ap_const_logic_1;
}

void filter::thread_Block_proc_U0_ap_continue() {
    Block_proc_U0_ap_continue = ap_const_logic_1;
}

void filter::thread_Block_proc_U0_ap_start() {
    Block_proc_U0_ap_start = ap_const_logic_1;
}

void filter::thread_GaussianBlur_U0_ap_continue() {
    GaussianBlur_U0_ap_continue = ap_const_logic_1;
}

void filter::thread_GaussianBlur_U0_ap_start() {
    GaussianBlur_U0_ap_start = start_for_GaussianBlur_U0_empty_n.read();
}

void filter::thread_GaussianBlur_U0_start_full_n() {
    GaussianBlur_U0_start_full_n = ap_const_logic_1;
}

void filter::thread_GaussianBlur_U0_start_write() {
    GaussianBlur_U0_start_write = ap_const_logic_0;
}

void filter::thread_Mat2AXIvideo_U0_ap_continue() {
    Mat2AXIvideo_U0_ap_continue = ap_const_logic_1;
}

void filter::thread_Mat2AXIvideo_U0_ap_start() {
    Mat2AXIvideo_U0_ap_start = start_for_Mat2AXIvideo_U0_empty_n.read();
}

void filter::thread_Mat2AXIvideo_U0_start_full_n() {
    Mat2AXIvideo_U0_start_full_n = ap_const_logic_1;
}

void filter::thread_Mat2AXIvideo_U0_start_write() {
    Mat2AXIvideo_U0_start_write = ap_const_logic_0;
}

void filter::thread_Threshold_U0_ap_continue() {
    Threshold_U0_ap_continue = ap_const_logic_1;
}

void filter::thread_Threshold_U0_ap_start() {
    Threshold_U0_ap_start = start_for_Threshold_U0_empty_n.read();
}

void filter::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void filter::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_0;
}

void filter::thread_start_for_GaussianBlur_U0_din() {
    start_for_GaussianBlur_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void filter::thread_start_for_Mat2AXIvideo_U0_din() {
    start_for_Mat2AXIvideo_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void filter::thread_start_for_Threshold_U0_din() {
    start_for_Threshold_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void filter::thread_video_in_TREADY() {
    video_in_TREADY = AXIvideo2Mat_U0_video_in_TREADY.read();
}

void filter::thread_video_out_TDATA() {
    video_out_TDATA = Mat2AXIvideo_U0_video_out_TDATA.read();
}

void filter::thread_video_out_TDEST() {
    video_out_TDEST = Mat2AXIvideo_U0_video_out_TDEST.read();
}

void filter::thread_video_out_TID() {
    video_out_TID = Mat2AXIvideo_U0_video_out_TID.read();
}

void filter::thread_video_out_TKEEP() {
    video_out_TKEEP = Mat2AXIvideo_U0_video_out_TKEEP.read();
}

void filter::thread_video_out_TLAST() {
    video_out_TLAST = Mat2AXIvideo_U0_video_out_TLAST.read();
}

void filter::thread_video_out_TSTRB() {
    video_out_TSTRB = Mat2AXIvideo_U0_video_out_TSTRB.read();
}

void filter::thread_video_out_TUSER() {
    video_out_TUSER = Mat2AXIvideo_U0_video_out_TUSER.read();
}

void filter::thread_video_out_TVALID() {
    video_out_TVALID = Mat2AXIvideo_U0_video_out_TVALID.read();
}

void filter::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"video_in_TDATA\" :  \"" << video_in_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TKEEP\" :  \"" << video_in_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TSTRB\" :  \"" << video_in_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TUSER\" :  \"" << video_in_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TLAST\" :  \"" << video_in_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TID\" :  \"" << video_in_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TDEST\" :  \"" << video_in_TDEST.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"video_out_TDATA\" :  \"" << video_out_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TKEEP\" :  \"" << video_out_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TSTRB\" :  \"" << video_out_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TUSER\" :  \"" << video_out_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TLAST\" :  \"" << video_out_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TID\" :  \"" << video_out_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TDEST\" :  \"" << video_out_TDEST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TVALID\" :  \"" << video_in_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_in_TREADY\" :  \"" << video_in_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TVALID\" :  \"" << video_out_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_out_TREADY\" :  \"" << video_out_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

