// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "filter.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_lv<32> filter::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<4> filter::ap_const_lv4_0 = "0000";
const sc_lv<1> filter::ap_const_lv1_0 = "0";
const sc_logic filter::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic filter::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> filter::ap_const_lv2_0 = "00";
const sc_lv<2> filter::ap_const_lv2_1 = "1";
const bool filter::ap_const_boolean_1 = true;

filter::filter(sc_module_name name) : sc_module(name), mVcdFile(0) {
    Block_proc_U0 = new Block_proc("Block_proc_U0");
    Block_proc_U0->ap_clk(ap_clk);
    Block_proc_U0->ap_rst(ap_rst_n_inv);
    Block_proc_U0->ap_start(Block_proc_U0_ap_start);
    Block_proc_U0->start_full_n(start_for_Threshold_U0_full_n);
    Block_proc_U0->ap_done(Block_proc_U0_ap_done);
    Block_proc_U0->ap_continue(Block_proc_U0_ap_continue);
    Block_proc_U0->ap_idle(Block_proc_U0_ap_idle);
    Block_proc_U0->ap_ready(Block_proc_U0_ap_ready);
    Block_proc_U0->start_out(Block_proc_U0_start_out);
    Block_proc_U0->start_write(Block_proc_U0_start_write);
    Block_proc_U0->img_0_rows_V_out_din(Block_proc_U0_img_0_rows_V_out_din);
    Block_proc_U0->img_0_rows_V_out_full_n(img_0_rows_V_c_full_n);
    Block_proc_U0->img_0_rows_V_out_write(Block_proc_U0_img_0_rows_V_out_write);
    Block_proc_U0->img_0_cols_V_out_din(Block_proc_U0_img_0_cols_V_out_din);
    Block_proc_U0->img_0_cols_V_out_full_n(img_0_cols_V_c_full_n);
    Block_proc_U0->img_0_cols_V_out_write(Block_proc_U0_img_0_cols_V_out_write);
    Block_proc_U0->img_3_rows_V_out_din(Block_proc_U0_img_3_rows_V_out_din);
    Block_proc_U0->img_3_rows_V_out_full_n(img_3_rows_V_c_full_n);
    Block_proc_U0->img_3_rows_V_out_write(Block_proc_U0_img_3_rows_V_out_write);
    Block_proc_U0->img_3_cols_V_out_din(Block_proc_U0_img_3_cols_V_out_din);
    Block_proc_U0->img_3_cols_V_out_full_n(img_3_cols_V_c_full_n);
    Block_proc_U0->img_3_cols_V_out_write(Block_proc_U0_img_3_cols_V_out_write);
    AXIvideo2Mat_U0 = new AXIvideo2Mat("AXIvideo2Mat_U0");
    AXIvideo2Mat_U0->ap_clk(ap_clk);
    AXIvideo2Mat_U0->ap_rst(ap_rst_n_inv);
    AXIvideo2Mat_U0->ap_start(AXIvideo2Mat_U0_ap_start);
    AXIvideo2Mat_U0->start_full_n(start_for_CvtColor_1_U0_full_n);
    AXIvideo2Mat_U0->ap_done(AXIvideo2Mat_U0_ap_done);
    AXIvideo2Mat_U0->ap_continue(AXIvideo2Mat_U0_ap_continue);
    AXIvideo2Mat_U0->ap_idle(AXIvideo2Mat_U0_ap_idle);
    AXIvideo2Mat_U0->ap_ready(AXIvideo2Mat_U0_ap_ready);
    AXIvideo2Mat_U0->start_out(AXIvideo2Mat_U0_start_out);
    AXIvideo2Mat_U0->start_write(AXIvideo2Mat_U0_start_write);
    AXIvideo2Mat_U0->video_in_TDATA(video_in_TDATA);
    AXIvideo2Mat_U0->video_in_TVALID(video_in_TVALID);
    AXIvideo2Mat_U0->video_in_TREADY(AXIvideo2Mat_U0_video_in_TREADY);
    AXIvideo2Mat_U0->video_in_TKEEP(video_in_TKEEP);
    AXIvideo2Mat_U0->video_in_TSTRB(video_in_TSTRB);
    AXIvideo2Mat_U0->video_in_TUSER(video_in_TUSER);
    AXIvideo2Mat_U0->video_in_TLAST(video_in_TLAST);
    AXIvideo2Mat_U0->video_in_TID(video_in_TID);
    AXIvideo2Mat_U0->video_in_TDEST(video_in_TDEST);
    AXIvideo2Mat_U0->img_rows_V_dout(img_0_rows_V_c_dout);
    AXIvideo2Mat_U0->img_rows_V_empty_n(img_0_rows_V_c_empty_n);
    AXIvideo2Mat_U0->img_rows_V_read(AXIvideo2Mat_U0_img_rows_V_read);
    AXIvideo2Mat_U0->img_cols_V_dout(img_0_cols_V_c_dout);
    AXIvideo2Mat_U0->img_cols_V_empty_n(img_0_cols_V_c_empty_n);
    AXIvideo2Mat_U0->img_cols_V_read(AXIvideo2Mat_U0_img_cols_V_read);
    AXIvideo2Mat_U0->img_data_stream_0_V_din(AXIvideo2Mat_U0_img_data_stream_0_V_din);
    AXIvideo2Mat_U0->img_data_stream_0_V_full_n(img_0_data_stream_0_full_n);
    AXIvideo2Mat_U0->img_data_stream_0_V_write(AXIvideo2Mat_U0_img_data_stream_0_V_write);
    AXIvideo2Mat_U0->img_data_stream_1_V_din(AXIvideo2Mat_U0_img_data_stream_1_V_din);
    AXIvideo2Mat_U0->img_data_stream_1_V_full_n(img_0_data_stream_1_full_n);
    AXIvideo2Mat_U0->img_data_stream_1_V_write(AXIvideo2Mat_U0_img_data_stream_1_V_write);
    AXIvideo2Mat_U0->img_data_stream_2_V_din(AXIvideo2Mat_U0_img_data_stream_2_V_din);
    AXIvideo2Mat_U0->img_data_stream_2_V_full_n(img_0_data_stream_2_full_n);
    AXIvideo2Mat_U0->img_data_stream_2_V_write(AXIvideo2Mat_U0_img_data_stream_2_V_write);
    AXIvideo2Mat_U0->img_rows_V_out_din(AXIvideo2Mat_U0_img_rows_V_out_din);
    AXIvideo2Mat_U0->img_rows_V_out_full_n(img_0_rows_V_c14_full_n);
    AXIvideo2Mat_U0->img_rows_V_out_write(AXIvideo2Mat_U0_img_rows_V_out_write);
    AXIvideo2Mat_U0->img_cols_V_out_din(AXIvideo2Mat_U0_img_cols_V_out_din);
    AXIvideo2Mat_U0->img_cols_V_out_full_n(img_0_cols_V_c15_full_n);
    AXIvideo2Mat_U0->img_cols_V_out_write(AXIvideo2Mat_U0_img_cols_V_out_write);
    CvtColor_1_U0 = new CvtColor_1("CvtColor_1_U0");
    CvtColor_1_U0->ap_clk(ap_clk);
    CvtColor_1_U0->ap_rst(ap_rst_n_inv);
    CvtColor_1_U0->ap_start(CvtColor_1_U0_ap_start);
    CvtColor_1_U0->start_full_n(start_for_GaussianBlur_U0_full_n);
    CvtColor_1_U0->ap_done(CvtColor_1_U0_ap_done);
    CvtColor_1_U0->ap_continue(CvtColor_1_U0_ap_continue);
    CvtColor_1_U0->ap_idle(CvtColor_1_U0_ap_idle);
    CvtColor_1_U0->ap_ready(CvtColor_1_U0_ap_ready);
    CvtColor_1_U0->start_out(CvtColor_1_U0_start_out);
    CvtColor_1_U0->start_write(CvtColor_1_U0_start_write);
    CvtColor_1_U0->p_src_rows_V_dout(img_0_rows_V_c14_dout);
    CvtColor_1_U0->p_src_rows_V_empty_n(img_0_rows_V_c14_empty_n);
    CvtColor_1_U0->p_src_rows_V_read(CvtColor_1_U0_p_src_rows_V_read);
    CvtColor_1_U0->p_src_cols_V_dout(img_0_cols_V_c15_dout);
    CvtColor_1_U0->p_src_cols_V_empty_n(img_0_cols_V_c15_empty_n);
    CvtColor_1_U0->p_src_cols_V_read(CvtColor_1_U0_p_src_cols_V_read);
    CvtColor_1_U0->p_src_data_stream_0_V_dout(img_0_data_stream_0_dout);
    CvtColor_1_U0->p_src_data_stream_0_V_empty_n(img_0_data_stream_0_empty_n);
    CvtColor_1_U0->p_src_data_stream_0_V_read(CvtColor_1_U0_p_src_data_stream_0_V_read);
    CvtColor_1_U0->p_src_data_stream_1_V_dout(img_0_data_stream_1_dout);
    CvtColor_1_U0->p_src_data_stream_1_V_empty_n(img_0_data_stream_1_empty_n);
    CvtColor_1_U0->p_src_data_stream_1_V_read(CvtColor_1_U0_p_src_data_stream_1_V_read);
    CvtColor_1_U0->p_src_data_stream_2_V_dout(img_0_data_stream_2_dout);
    CvtColor_1_U0->p_src_data_stream_2_V_empty_n(img_0_data_stream_2_empty_n);
    CvtColor_1_U0->p_src_data_stream_2_V_read(CvtColor_1_U0_p_src_data_stream_2_V_read);
    CvtColor_1_U0->p_dst_data_stream_V_din(CvtColor_1_U0_p_dst_data_stream_V_din);
    CvtColor_1_U0->p_dst_data_stream_V_full_n(img_1_data_stream_0_full_n);
    CvtColor_1_U0->p_dst_data_stream_V_write(CvtColor_1_U0_p_dst_data_stream_V_write);
    GaussianBlur_U0 = new GaussianBlur("GaussianBlur_U0");
    GaussianBlur_U0->ap_clk(ap_clk);
    GaussianBlur_U0->ap_rst(ap_rst_n_inv);
    GaussianBlur_U0->ap_start(GaussianBlur_U0_ap_start);
    GaussianBlur_U0->ap_done(GaussianBlur_U0_ap_done);
    GaussianBlur_U0->ap_continue(GaussianBlur_U0_ap_continue);
    GaussianBlur_U0->ap_idle(GaussianBlur_U0_ap_idle);
    GaussianBlur_U0->ap_ready(GaussianBlur_U0_ap_ready);
    GaussianBlur_U0->p_src_data_stream_V_dout(img_1_data_stream_0_dout);
    GaussianBlur_U0->p_src_data_stream_V_empty_n(img_1_data_stream_0_empty_n);
    GaussianBlur_U0->p_src_data_stream_V_read(GaussianBlur_U0_p_src_data_stream_V_read);
    GaussianBlur_U0->p_dst_data_stream_V_din(GaussianBlur_U0_p_dst_data_stream_V_din);
    GaussianBlur_U0->p_dst_data_stream_V_full_n(img_2_data_stream_0_full_n);
    GaussianBlur_U0->p_dst_data_stream_V_write(GaussianBlur_U0_p_dst_data_stream_V_write);
    Threshold_U0 = new Threshold("Threshold_U0");
    Threshold_U0->ap_clk(ap_clk);
    Threshold_U0->ap_rst(ap_rst_n_inv);
    Threshold_U0->ap_start(Threshold_U0_ap_start);
    Threshold_U0->start_full_n(start_for_CvtColor_U0_full_n);
    Threshold_U0->ap_done(Threshold_U0_ap_done);
    Threshold_U0->ap_continue(Threshold_U0_ap_continue);
    Threshold_U0->ap_idle(Threshold_U0_ap_idle);
    Threshold_U0->ap_ready(Threshold_U0_ap_ready);
    Threshold_U0->start_out(Threshold_U0_start_out);
    Threshold_U0->start_write(Threshold_U0_start_write);
    Threshold_U0->src_data_stream_V_dout(img_2_data_stream_0_dout);
    Threshold_U0->src_data_stream_V_empty_n(img_2_data_stream_0_empty_n);
    Threshold_U0->src_data_stream_V_read(Threshold_U0_src_data_stream_V_read);
    Threshold_U0->dst_rows_V_dout(img_3_rows_V_c_dout);
    Threshold_U0->dst_rows_V_empty_n(img_3_rows_V_c_empty_n);
    Threshold_U0->dst_rows_V_read(Threshold_U0_dst_rows_V_read);
    Threshold_U0->dst_cols_V_dout(img_3_cols_V_c_dout);
    Threshold_U0->dst_cols_V_empty_n(img_3_cols_V_c_empty_n);
    Threshold_U0->dst_cols_V_read(Threshold_U0_dst_cols_V_read);
    Threshold_U0->dst_data_stream_V_din(Threshold_U0_dst_data_stream_V_din);
    Threshold_U0->dst_data_stream_V_full_n(img_3_data_stream_0_full_n);
    Threshold_U0->dst_data_stream_V_write(Threshold_U0_dst_data_stream_V_write);
    Threshold_U0->dst_rows_V_out_din(Threshold_U0_dst_rows_V_out_din);
    Threshold_U0->dst_rows_V_out_full_n(img_3_rows_V_c16_full_n);
    Threshold_U0->dst_rows_V_out_write(Threshold_U0_dst_rows_V_out_write);
    Threshold_U0->dst_cols_V_out_din(Threshold_U0_dst_cols_V_out_din);
    Threshold_U0->dst_cols_V_out_full_n(img_3_cols_V_c17_full_n);
    Threshold_U0->dst_cols_V_out_write(Threshold_U0_dst_cols_V_out_write);
    CvtColor_U0 = new CvtColor("CvtColor_U0");
    CvtColor_U0->ap_clk(ap_clk);
    CvtColor_U0->ap_rst(ap_rst_n_inv);
    CvtColor_U0->ap_start(CvtColor_U0_ap_start);
    CvtColor_U0->start_full_n(start_for_Mat2AXIvideo_U0_full_n);
    CvtColor_U0->ap_done(CvtColor_U0_ap_done);
    CvtColor_U0->ap_continue(CvtColor_U0_ap_continue);
    CvtColor_U0->ap_idle(CvtColor_U0_ap_idle);
    CvtColor_U0->ap_ready(CvtColor_U0_ap_ready);
    CvtColor_U0->start_out(CvtColor_U0_start_out);
    CvtColor_U0->start_write(CvtColor_U0_start_write);
    CvtColor_U0->p_src_rows_V_dout(img_3_rows_V_c16_dout);
    CvtColor_U0->p_src_rows_V_empty_n(img_3_rows_V_c16_empty_n);
    CvtColor_U0->p_src_rows_V_read(CvtColor_U0_p_src_rows_V_read);
    CvtColor_U0->p_src_cols_V_dout(img_3_cols_V_c17_dout);
    CvtColor_U0->p_src_cols_V_empty_n(img_3_cols_V_c17_empty_n);
    CvtColor_U0->p_src_cols_V_read(CvtColor_U0_p_src_cols_V_read);
    CvtColor_U0->p_src_data_stream_V_dout(img_3_data_stream_0_dout);
    CvtColor_U0->p_src_data_stream_V_empty_n(img_3_data_stream_0_empty_n);
    CvtColor_U0->p_src_data_stream_V_read(CvtColor_U0_p_src_data_stream_V_read);
    CvtColor_U0->p_dst_data_stream_0_V_din(CvtColor_U0_p_dst_data_stream_0_V_din);
    CvtColor_U0->p_dst_data_stream_0_V_full_n(img_4_data_stream_0_full_n);
    CvtColor_U0->p_dst_data_stream_0_V_write(CvtColor_U0_p_dst_data_stream_0_V_write);
    CvtColor_U0->p_dst_data_stream_1_V_din(CvtColor_U0_p_dst_data_stream_1_V_din);
    CvtColor_U0->p_dst_data_stream_1_V_full_n(img_4_data_stream_1_full_n);
    CvtColor_U0->p_dst_data_stream_1_V_write(CvtColor_U0_p_dst_data_stream_1_V_write);
    CvtColor_U0->p_dst_data_stream_2_V_din(CvtColor_U0_p_dst_data_stream_2_V_din);
    CvtColor_U0->p_dst_data_stream_2_V_full_n(img_4_data_stream_2_full_n);
    CvtColor_U0->p_dst_data_stream_2_V_write(CvtColor_U0_p_dst_data_stream_2_V_write);
    Mat2AXIvideo_U0 = new Mat2AXIvideo("Mat2AXIvideo_U0");
    Mat2AXIvideo_U0->ap_clk(ap_clk);
    Mat2AXIvideo_U0->ap_rst(ap_rst_n_inv);
    Mat2AXIvideo_U0->ap_start(Mat2AXIvideo_U0_ap_start);
    Mat2AXIvideo_U0->ap_done(Mat2AXIvideo_U0_ap_done);
    Mat2AXIvideo_U0->ap_continue(Mat2AXIvideo_U0_ap_continue);
    Mat2AXIvideo_U0->ap_idle(Mat2AXIvideo_U0_ap_idle);
    Mat2AXIvideo_U0->ap_ready(Mat2AXIvideo_U0_ap_ready);
    Mat2AXIvideo_U0->img_data_stream_0_V_dout(img_4_data_stream_0_dout);
    Mat2AXIvideo_U0->img_data_stream_0_V_empty_n(img_4_data_stream_0_empty_n);
    Mat2AXIvideo_U0->img_data_stream_0_V_read(Mat2AXIvideo_U0_img_data_stream_0_V_read);
    Mat2AXIvideo_U0->img_data_stream_1_V_dout(img_4_data_stream_1_dout);
    Mat2AXIvideo_U0->img_data_stream_1_V_empty_n(img_4_data_stream_1_empty_n);
    Mat2AXIvideo_U0->img_data_stream_1_V_read(Mat2AXIvideo_U0_img_data_stream_1_V_read);
    Mat2AXIvideo_U0->img_data_stream_2_V_dout(img_4_data_stream_2_dout);
    Mat2AXIvideo_U0->img_data_stream_2_V_empty_n(img_4_data_stream_2_empty_n);
    Mat2AXIvideo_U0->img_data_stream_2_V_read(Mat2AXIvideo_U0_img_data_stream_2_V_read);
    Mat2AXIvideo_U0->video_out_TDATA(Mat2AXIvideo_U0_video_out_TDATA);
    Mat2AXIvideo_U0->video_out_TVALID(Mat2AXIvideo_U0_video_out_TVALID);
    Mat2AXIvideo_U0->video_out_TREADY(video_out_TREADY);
    Mat2AXIvideo_U0->video_out_TKEEP(Mat2AXIvideo_U0_video_out_TKEEP);
    Mat2AXIvideo_U0->video_out_TSTRB(Mat2AXIvideo_U0_video_out_TSTRB);
    Mat2AXIvideo_U0->video_out_TUSER(Mat2AXIvideo_U0_video_out_TUSER);
    Mat2AXIvideo_U0->video_out_TLAST(Mat2AXIvideo_U0_video_out_TLAST);
    Mat2AXIvideo_U0->video_out_TID(Mat2AXIvideo_U0_video_out_TID);
    Mat2AXIvideo_U0->video_out_TDEST(Mat2AXIvideo_U0_video_out_TDEST);
    img_0_rows_V_c_U = new fifo_w10_d2_A("img_0_rows_V_c_U");
    img_0_rows_V_c_U->clk(ap_clk);
    img_0_rows_V_c_U->reset(ap_rst_n_inv);
    img_0_rows_V_c_U->if_read_ce(ap_var_for_const0);
    img_0_rows_V_c_U->if_write_ce(ap_var_for_const0);
    img_0_rows_V_c_U->if_din(Block_proc_U0_img_0_rows_V_out_din);
    img_0_rows_V_c_U->if_full_n(img_0_rows_V_c_full_n);
    img_0_rows_V_c_U->if_write(Block_proc_U0_img_0_rows_V_out_write);
    img_0_rows_V_c_U->if_dout(img_0_rows_V_c_dout);
    img_0_rows_V_c_U->if_empty_n(img_0_rows_V_c_empty_n);
    img_0_rows_V_c_U->if_read(AXIvideo2Mat_U0_img_rows_V_read);
    img_0_cols_V_c_U = new fifo_w11_d2_A("img_0_cols_V_c_U");
    img_0_cols_V_c_U->clk(ap_clk);
    img_0_cols_V_c_U->reset(ap_rst_n_inv);
    img_0_cols_V_c_U->if_read_ce(ap_var_for_const0);
    img_0_cols_V_c_U->if_write_ce(ap_var_for_const0);
    img_0_cols_V_c_U->if_din(Block_proc_U0_img_0_cols_V_out_din);
    img_0_cols_V_c_U->if_full_n(img_0_cols_V_c_full_n);
    img_0_cols_V_c_U->if_write(Block_proc_U0_img_0_cols_V_out_write);
    img_0_cols_V_c_U->if_dout(img_0_cols_V_c_dout);
    img_0_cols_V_c_U->if_empty_n(img_0_cols_V_c_empty_n);
    img_0_cols_V_c_U->if_read(AXIvideo2Mat_U0_img_cols_V_read);
    img_3_rows_V_c_U = new fifo_w10_d5_A("img_3_rows_V_c_U");
    img_3_rows_V_c_U->clk(ap_clk);
    img_3_rows_V_c_U->reset(ap_rst_n_inv);
    img_3_rows_V_c_U->if_read_ce(ap_var_for_const0);
    img_3_rows_V_c_U->if_write_ce(ap_var_for_const0);
    img_3_rows_V_c_U->if_din(Block_proc_U0_img_3_rows_V_out_din);
    img_3_rows_V_c_U->if_full_n(img_3_rows_V_c_full_n);
    img_3_rows_V_c_U->if_write(Block_proc_U0_img_3_rows_V_out_write);
    img_3_rows_V_c_U->if_dout(img_3_rows_V_c_dout);
    img_3_rows_V_c_U->if_empty_n(img_3_rows_V_c_empty_n);
    img_3_rows_V_c_U->if_read(Threshold_U0_dst_rows_V_read);
    img_3_cols_V_c_U = new fifo_w11_d5_A("img_3_cols_V_c_U");
    img_3_cols_V_c_U->clk(ap_clk);
    img_3_cols_V_c_U->reset(ap_rst_n_inv);
    img_3_cols_V_c_U->if_read_ce(ap_var_for_const0);
    img_3_cols_V_c_U->if_write_ce(ap_var_for_const0);
    img_3_cols_V_c_U->if_din(Block_proc_U0_img_3_cols_V_out_din);
    img_3_cols_V_c_U->if_full_n(img_3_cols_V_c_full_n);
    img_3_cols_V_c_U->if_write(Block_proc_U0_img_3_cols_V_out_write);
    img_3_cols_V_c_U->if_dout(img_3_cols_V_c_dout);
    img_3_cols_V_c_U->if_empty_n(img_3_cols_V_c_empty_n);
    img_3_cols_V_c_U->if_read(Threshold_U0_dst_cols_V_read);
    img_0_data_stream_0_U = new fifo_w8_d2_A("img_0_data_stream_0_U");
    img_0_data_stream_0_U->clk(ap_clk);
    img_0_data_stream_0_U->reset(ap_rst_n_inv);
    img_0_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_0_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_0_data_stream_0_U->if_din(AXIvideo2Mat_U0_img_data_stream_0_V_din);
    img_0_data_stream_0_U->if_full_n(img_0_data_stream_0_full_n);
    img_0_data_stream_0_U->if_write(AXIvideo2Mat_U0_img_data_stream_0_V_write);
    img_0_data_stream_0_U->if_dout(img_0_data_stream_0_dout);
    img_0_data_stream_0_U->if_empty_n(img_0_data_stream_0_empty_n);
    img_0_data_stream_0_U->if_read(CvtColor_1_U0_p_src_data_stream_0_V_read);
    img_0_data_stream_1_U = new fifo_w8_d2_A("img_0_data_stream_1_U");
    img_0_data_stream_1_U->clk(ap_clk);
    img_0_data_stream_1_U->reset(ap_rst_n_inv);
    img_0_data_stream_1_U->if_read_ce(ap_var_for_const0);
    img_0_data_stream_1_U->if_write_ce(ap_var_for_const0);
    img_0_data_stream_1_U->if_din(AXIvideo2Mat_U0_img_data_stream_1_V_din);
    img_0_data_stream_1_U->if_full_n(img_0_data_stream_1_full_n);
    img_0_data_stream_1_U->if_write(AXIvideo2Mat_U0_img_data_stream_1_V_write);
    img_0_data_stream_1_U->if_dout(img_0_data_stream_1_dout);
    img_0_data_stream_1_U->if_empty_n(img_0_data_stream_1_empty_n);
    img_0_data_stream_1_U->if_read(CvtColor_1_U0_p_src_data_stream_1_V_read);
    img_0_data_stream_2_U = new fifo_w8_d2_A("img_0_data_stream_2_U");
    img_0_data_stream_2_U->clk(ap_clk);
    img_0_data_stream_2_U->reset(ap_rst_n_inv);
    img_0_data_stream_2_U->if_read_ce(ap_var_for_const0);
    img_0_data_stream_2_U->if_write_ce(ap_var_for_const0);
    img_0_data_stream_2_U->if_din(AXIvideo2Mat_U0_img_data_stream_2_V_din);
    img_0_data_stream_2_U->if_full_n(img_0_data_stream_2_full_n);
    img_0_data_stream_2_U->if_write(AXIvideo2Mat_U0_img_data_stream_2_V_write);
    img_0_data_stream_2_U->if_dout(img_0_data_stream_2_dout);
    img_0_data_stream_2_U->if_empty_n(img_0_data_stream_2_empty_n);
    img_0_data_stream_2_U->if_read(CvtColor_1_U0_p_src_data_stream_2_V_read);
    img_0_rows_V_c14_U = new fifo_w10_d2_A("img_0_rows_V_c14_U");
    img_0_rows_V_c14_U->clk(ap_clk);
    img_0_rows_V_c14_U->reset(ap_rst_n_inv);
    img_0_rows_V_c14_U->if_read_ce(ap_var_for_const0);
    img_0_rows_V_c14_U->if_write_ce(ap_var_for_const0);
    img_0_rows_V_c14_U->if_din(AXIvideo2Mat_U0_img_rows_V_out_din);
    img_0_rows_V_c14_U->if_full_n(img_0_rows_V_c14_full_n);
    img_0_rows_V_c14_U->if_write(AXIvideo2Mat_U0_img_rows_V_out_write);
    img_0_rows_V_c14_U->if_dout(img_0_rows_V_c14_dout);
    img_0_rows_V_c14_U->if_empty_n(img_0_rows_V_c14_empty_n);
    img_0_rows_V_c14_U->if_read(CvtColor_1_U0_p_src_rows_V_read);
    img_0_cols_V_c15_U = new fifo_w11_d2_A("img_0_cols_V_c15_U");
    img_0_cols_V_c15_U->clk(ap_clk);
    img_0_cols_V_c15_U->reset(ap_rst_n_inv);
    img_0_cols_V_c15_U->if_read_ce(ap_var_for_const0);
    img_0_cols_V_c15_U->if_write_ce(ap_var_for_const0);
    img_0_cols_V_c15_U->if_din(AXIvideo2Mat_U0_img_cols_V_out_din);
    img_0_cols_V_c15_U->if_full_n(img_0_cols_V_c15_full_n);
    img_0_cols_V_c15_U->if_write(AXIvideo2Mat_U0_img_cols_V_out_write);
    img_0_cols_V_c15_U->if_dout(img_0_cols_V_c15_dout);
    img_0_cols_V_c15_U->if_empty_n(img_0_cols_V_c15_empty_n);
    img_0_cols_V_c15_U->if_read(CvtColor_1_U0_p_src_cols_V_read);
    img_1_data_stream_0_U = new fifo_w8_d2_A("img_1_data_stream_0_U");
    img_1_data_stream_0_U->clk(ap_clk);
    img_1_data_stream_0_U->reset(ap_rst_n_inv);
    img_1_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_1_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_1_data_stream_0_U->if_din(CvtColor_1_U0_p_dst_data_stream_V_din);
    img_1_data_stream_0_U->if_full_n(img_1_data_stream_0_full_n);
    img_1_data_stream_0_U->if_write(CvtColor_1_U0_p_dst_data_stream_V_write);
    img_1_data_stream_0_U->if_dout(img_1_data_stream_0_dout);
    img_1_data_stream_0_U->if_empty_n(img_1_data_stream_0_empty_n);
    img_1_data_stream_0_U->if_read(GaussianBlur_U0_p_src_data_stream_V_read);
    img_2_data_stream_0_U = new fifo_w8_d2_A("img_2_data_stream_0_U");
    img_2_data_stream_0_U->clk(ap_clk);
    img_2_data_stream_0_U->reset(ap_rst_n_inv);
    img_2_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_2_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_2_data_stream_0_U->if_din(GaussianBlur_U0_p_dst_data_stream_V_din);
    img_2_data_stream_0_U->if_full_n(img_2_data_stream_0_full_n);
    img_2_data_stream_0_U->if_write(GaussianBlur_U0_p_dst_data_stream_V_write);
    img_2_data_stream_0_U->if_dout(img_2_data_stream_0_dout);
    img_2_data_stream_0_U->if_empty_n(img_2_data_stream_0_empty_n);
    img_2_data_stream_0_U->if_read(Threshold_U0_src_data_stream_V_read);
    img_3_data_stream_0_U = new fifo_w8_d2_A("img_3_data_stream_0_U");
    img_3_data_stream_0_U->clk(ap_clk);
    img_3_data_stream_0_U->reset(ap_rst_n_inv);
    img_3_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_3_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_3_data_stream_0_U->if_din(Threshold_U0_dst_data_stream_V_din);
    img_3_data_stream_0_U->if_full_n(img_3_data_stream_0_full_n);
    img_3_data_stream_0_U->if_write(Threshold_U0_dst_data_stream_V_write);
    img_3_data_stream_0_U->if_dout(img_3_data_stream_0_dout);
    img_3_data_stream_0_U->if_empty_n(img_3_data_stream_0_empty_n);
    img_3_data_stream_0_U->if_read(CvtColor_U0_p_src_data_stream_V_read);
    img_3_rows_V_c16_U = new fifo_w10_d2_A("img_3_rows_V_c16_U");
    img_3_rows_V_c16_U->clk(ap_clk);
    img_3_rows_V_c16_U->reset(ap_rst_n_inv);
    img_3_rows_V_c16_U->if_read_ce(ap_var_for_const0);
    img_3_rows_V_c16_U->if_write_ce(ap_var_for_const0);
    img_3_rows_V_c16_U->if_din(Threshold_U0_dst_rows_V_out_din);
    img_3_rows_V_c16_U->if_full_n(img_3_rows_V_c16_full_n);
    img_3_rows_V_c16_U->if_write(Threshold_U0_dst_rows_V_out_write);
    img_3_rows_V_c16_U->if_dout(img_3_rows_V_c16_dout);
    img_3_rows_V_c16_U->if_empty_n(img_3_rows_V_c16_empty_n);
    img_3_rows_V_c16_U->if_read(CvtColor_U0_p_src_rows_V_read);
    img_3_cols_V_c17_U = new fifo_w11_d2_A("img_3_cols_V_c17_U");
    img_3_cols_V_c17_U->clk(ap_clk);
    img_3_cols_V_c17_U->reset(ap_rst_n_inv);
    img_3_cols_V_c17_U->if_read_ce(ap_var_for_const0);
    img_3_cols_V_c17_U->if_write_ce(ap_var_for_const0);
    img_3_cols_V_c17_U->if_din(Threshold_U0_dst_cols_V_out_din);
    img_3_cols_V_c17_U->if_full_n(img_3_cols_V_c17_full_n);
    img_3_cols_V_c17_U->if_write(Threshold_U0_dst_cols_V_out_write);
    img_3_cols_V_c17_U->if_dout(img_3_cols_V_c17_dout);
    img_3_cols_V_c17_U->if_empty_n(img_3_cols_V_c17_empty_n);
    img_3_cols_V_c17_U->if_read(CvtColor_U0_p_src_cols_V_read);
    img_4_data_stream_0_U = new fifo_w8_d2_A("img_4_data_stream_0_U");
    img_4_data_stream_0_U->clk(ap_clk);
    img_4_data_stream_0_U->reset(ap_rst_n_inv);
    img_4_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_4_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_4_data_stream_0_U->if_din(CvtColor_U0_p_dst_data_stream_0_V_din);
    img_4_data_stream_0_U->if_full_n(img_4_data_stream_0_full_n);
    img_4_data_stream_0_U->if_write(CvtColor_U0_p_dst_data_stream_0_V_write);
    img_4_data_stream_0_U->if_dout(img_4_data_stream_0_dout);
    img_4_data_stream_0_U->if_empty_n(img_4_data_stream_0_empty_n);
    img_4_data_stream_0_U->if_read(Mat2AXIvideo_U0_img_data_stream_0_V_read);
    img_4_data_stream_1_U = new fifo_w8_d2_A("img_4_data_stream_1_U");
    img_4_data_stream_1_U->clk(ap_clk);
    img_4_data_stream_1_U->reset(ap_rst_n_inv);
    img_4_data_stream_1_U->if_read_ce(ap_var_for_const0);
    img_4_data_stream_1_U->if_write_ce(ap_var_for_const0);
    img_4_data_stream_1_U->if_din(CvtColor_U0_p_dst_data_stream_1_V_din);
    img_4_data_stream_1_U->if_full_n(img_4_data_stream_1_full_n);
    img_4_data_stream_1_U->if_write(CvtColor_U0_p_dst_data_stream_1_V_write);
    img_4_data_stream_1_U->if_dout(img_4_data_stream_1_dout);
    img_4_data_stream_1_U->if_empty_n(img_4_data_stream_1_empty_n);
    img_4_data_stream_1_U->if_read(Mat2AXIvideo_U0_img_data_stream_1_V_read);
    img_4_data_stream_2_U = new fifo_w8_d2_A("img_4_data_stream_2_U");
    img_4_data_stream_2_U->clk(ap_clk);
    img_4_data_stream_2_U->reset(ap_rst_n_inv);
    img_4_data_stream_2_U->if_read_ce(ap_var_for_const0);
    img_4_data_stream_2_U->if_write_ce(ap_var_for_const0);
    img_4_data_stream_2_U->if_din(CvtColor_U0_p_dst_data_stream_2_V_din);
    img_4_data_stream_2_U->if_full_n(img_4_data_stream_2_full_n);
    img_4_data_stream_2_U->if_write(CvtColor_U0_p_dst_data_stream_2_V_write);
    img_4_data_stream_2_U->if_dout(img_4_data_stream_2_dout);
    img_4_data_stream_2_U->if_empty_n(img_4_data_stream_2_empty_n);
    img_4_data_stream_2_U->if_read(Mat2AXIvideo_U0_img_data_stream_2_V_read);
    start_for_Threshoyd2_U = new start_for_Threshoyd2("start_for_Threshoyd2_U");
    start_for_Threshoyd2_U->clk(ap_clk);
    start_for_Threshoyd2_U->reset(ap_rst_n_inv);
    start_for_Threshoyd2_U->if_read_ce(ap_var_for_const0);
    start_for_Threshoyd2_U->if_write_ce(ap_var_for_const0);
    start_for_Threshoyd2_U->if_din(start_for_Threshold_U0_din);
    start_for_Threshoyd2_U->if_full_n(start_for_Threshold_U0_full_n);
    start_for_Threshoyd2_U->if_write(Block_proc_U0_start_write);
    start_for_Threshoyd2_U->if_dout(start_for_Threshold_U0_dout);
    start_for_Threshoyd2_U->if_empty_n(start_for_Threshold_U0_empty_n);
    start_for_Threshoyd2_U->if_read(Threshold_U0_ap_ready);
    start_for_CvtColozec_U = new start_for_CvtColozec("start_for_CvtColozec_U");
    start_for_CvtColozec_U->clk(ap_clk);
    start_for_CvtColozec_U->reset(ap_rst_n_inv);
    start_for_CvtColozec_U->if_read_ce(ap_var_for_const0);
    start_for_CvtColozec_U->if_write_ce(ap_var_for_const0);
    start_for_CvtColozec_U->if_din(start_for_CvtColor_1_U0_din);
    start_for_CvtColozec_U->if_full_n(start_for_CvtColor_1_U0_full_n);
    start_for_CvtColozec_U->if_write(AXIvideo2Mat_U0_start_write);
    start_for_CvtColozec_U->if_dout(start_for_CvtColor_1_U0_dout);
    start_for_CvtColozec_U->if_empty_n(start_for_CvtColor_1_U0_empty_n);
    start_for_CvtColozec_U->if_read(CvtColor_1_U0_ap_ready);
    start_for_GaussiaAem_U = new start_for_GaussiaAem("start_for_GaussiaAem_U");
    start_for_GaussiaAem_U->clk(ap_clk);
    start_for_GaussiaAem_U->reset(ap_rst_n_inv);
    start_for_GaussiaAem_U->if_read_ce(ap_var_for_const0);
    start_for_GaussiaAem_U->if_write_ce(ap_var_for_const0);
    start_for_GaussiaAem_U->if_din(start_for_GaussianBlur_U0_din);
    start_for_GaussiaAem_U->if_full_n(start_for_GaussianBlur_U0_full_n);
    start_for_GaussiaAem_U->if_write(CvtColor_1_U0_start_write);
    start_for_GaussiaAem_U->if_dout(start_for_GaussianBlur_U0_dout);
    start_for_GaussiaAem_U->if_empty_n(start_for_GaussianBlur_U0_empty_n);
    start_for_GaussiaAem_U->if_read(GaussianBlur_U0_ap_ready);
    start_for_CvtColoBew_U = new start_for_CvtColoBew("start_for_CvtColoBew_U");
    start_for_CvtColoBew_U->clk(ap_clk);
    start_for_CvtColoBew_U->reset(ap_rst_n_inv);
    start_for_CvtColoBew_U->if_read_ce(ap_var_for_const0);
    start_for_CvtColoBew_U->if_write_ce(ap_var_for_const0);
    start_for_CvtColoBew_U->if_din(start_for_CvtColor_U0_din);
    start_for_CvtColoBew_U->if_full_n(start_for_CvtColor_U0_full_n);
    start_for_CvtColoBew_U->if_write(Threshold_U0_start_write);
    start_for_CvtColoBew_U->if_dout(start_for_CvtColor_U0_dout);
    start_for_CvtColoBew_U->if_empty_n(start_for_CvtColor_U0_empty_n);
    start_for_CvtColoBew_U->if_read(CvtColor_U0_ap_ready);
    start_for_Mat2AXICeG_U = new start_for_Mat2AXICeG("start_for_Mat2AXICeG_U");
    start_for_Mat2AXICeG_U->clk(ap_clk);
    start_for_Mat2AXICeG_U->reset(ap_rst_n_inv);
    start_for_Mat2AXICeG_U->if_read_ce(ap_var_for_const0);
    start_for_Mat2AXICeG_U->if_write_ce(ap_var_for_const0);
    start_for_Mat2AXICeG_U->if_din(start_for_Mat2AXIvideo_U0_din);
    start_for_Mat2AXICeG_U->if_full_n(start_for_Mat2AXIvideo_U0_full_n);
    start_for_Mat2AXICeG_U->if_write(CvtColor_U0_start_write);
    start_for_Mat2AXICeG_U->if_dout(start_for_Mat2AXIvideo_U0_dout);
    start_for_Mat2AXICeG_U->if_empty_n(start_for_Mat2AXIvideo_U0_empty_n);
    start_for_Mat2AXICeG_U->if_read(Mat2AXIvideo_U0_ap_ready);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_AXIvideo2Mat_U0_ap_continue);

    SC_METHOD(thread_AXIvideo2Mat_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_AXIvideo2Mat_U0_ap_ready );

    SC_METHOD(thread_Block_proc_U0_ap_continue);

    SC_METHOD(thread_Block_proc_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_Block_proc_U0_ap_ready );

    SC_METHOD(thread_CvtColor_1_U0_ap_continue);

    SC_METHOD(thread_CvtColor_1_U0_ap_start);
    sensitive << ( start_for_CvtColor_1_U0_empty_n );

    SC_METHOD(thread_CvtColor_U0_ap_continue);

    SC_METHOD(thread_CvtColor_U0_ap_start);
    sensitive << ( start_for_CvtColor_U0_empty_n );

    SC_METHOD(thread_GaussianBlur_U0_ap_continue);

    SC_METHOD(thread_GaussianBlur_U0_ap_start);
    sensitive << ( start_for_GaussianBlur_U0_empty_n );

    SC_METHOD(thread_GaussianBlur_U0_start_full_n);

    SC_METHOD(thread_GaussianBlur_U0_start_write);

    SC_METHOD(thread_Mat2AXIvideo_U0_ap_continue);

    SC_METHOD(thread_Mat2AXIvideo_U0_ap_start);
    sensitive << ( start_for_Mat2AXIvideo_U0_empty_n );

    SC_METHOD(thread_Mat2AXIvideo_U0_start_full_n);

    SC_METHOD(thread_Mat2AXIvideo_U0_start_write);

    SC_METHOD(thread_Threshold_U0_ap_continue);

    SC_METHOD(thread_Threshold_U0_ap_start);
    sensitive << ( start_for_Threshold_U0_empty_n );

    SC_METHOD(thread_ap_done);
    sensitive << ( Mat2AXIvideo_U0_ap_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( Block_proc_U0_ap_idle );
    sensitive << ( AXIvideo2Mat_U0_ap_idle );
    sensitive << ( CvtColor_1_U0_ap_idle );
    sensitive << ( GaussianBlur_U0_ap_idle );
    sensitive << ( Threshold_U0_ap_idle );
    sensitive << ( CvtColor_U0_ap_idle );
    sensitive << ( Mat2AXIvideo_U0_ap_idle );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sync_ready );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_AXIvideo2Mat_U0_ap_ready);
    sensitive << ( AXIvideo2Mat_U0_ap_ready );
    sensitive << ( ap_sync_reg_AXIvideo2Mat_U0_ap_ready );

    SC_METHOD(thread_ap_sync_Block_proc_U0_ap_ready);
    sensitive << ( Block_proc_U0_ap_ready );
    sensitive << ( ap_sync_reg_Block_proc_U0_ap_ready );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_ap_sync_done);
    sensitive << ( Mat2AXIvideo_U0_ap_done );

    SC_METHOD(thread_ap_sync_ready);
    sensitive << ( ap_sync_Block_proc_U0_ap_ready );
    sensitive << ( ap_sync_AXIvideo2Mat_U0_ap_ready );

    SC_METHOD(thread_start_for_CvtColor_1_U0_din);

    SC_METHOD(thread_start_for_CvtColor_U0_din);

    SC_METHOD(thread_start_for_GaussianBlur_U0_din);

    SC_METHOD(thread_start_for_Mat2AXIvideo_U0_din);

    SC_METHOD(thread_start_for_Threshold_U0_din);

    SC_METHOD(thread_video_in_TREADY);
    sensitive << ( AXIvideo2Mat_U0_video_in_TREADY );

    SC_METHOD(thread_video_out_TDATA);
    sensitive << ( Mat2AXIvideo_U0_video_out_TDATA );

    SC_METHOD(thread_video_out_TDEST);
    sensitive << ( Mat2AXIvideo_U0_video_out_TDEST );

    SC_METHOD(thread_video_out_TID);
    sensitive << ( Mat2AXIvideo_U0_video_out_TID );

    SC_METHOD(thread_video_out_TKEEP);
    sensitive << ( Mat2AXIvideo_U0_video_out_TKEEP );

    SC_METHOD(thread_video_out_TLAST);
    sensitive << ( Mat2AXIvideo_U0_video_out_TLAST );

    SC_METHOD(thread_video_out_TSTRB);
    sensitive << ( Mat2AXIvideo_U0_video_out_TSTRB );

    SC_METHOD(thread_video_out_TUSER);
    sensitive << ( Mat2AXIvideo_U0_video_out_TUSER );

    SC_METHOD(thread_video_out_TVALID);
    sensitive << ( Mat2AXIvideo_U0_video_out_TVALID );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_sync_reg_Block_proc_U0_ap_ready = SC_LOGIC_0;
    Block_proc_U0_ap_ready_count = "00";
    ap_sync_reg_AXIvideo2Mat_U0_ap_ready = SC_LOGIC_0;
    AXIvideo2Mat_U0_ap_ready_count = "00";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "filter_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, video_in_TDATA, "(port)video_in_TDATA");
    sc_trace(mVcdFile, video_in_TKEEP, "(port)video_in_TKEEP");
    sc_trace(mVcdFile, video_in_TSTRB, "(port)video_in_TSTRB");
    sc_trace(mVcdFile, video_in_TUSER, "(port)video_in_TUSER");
    sc_trace(mVcdFile, video_in_TLAST, "(port)video_in_TLAST");
    sc_trace(mVcdFile, video_in_TID, "(port)video_in_TID");
    sc_trace(mVcdFile, video_in_TDEST, "(port)video_in_TDEST");
    sc_trace(mVcdFile, video_out_TDATA, "(port)video_out_TDATA");
    sc_trace(mVcdFile, video_out_TKEEP, "(port)video_out_TKEEP");
    sc_trace(mVcdFile, video_out_TSTRB, "(port)video_out_TSTRB");
    sc_trace(mVcdFile, video_out_TUSER, "(port)video_out_TUSER");
    sc_trace(mVcdFile, video_out_TLAST, "(port)video_out_TLAST");
    sc_trace(mVcdFile, video_out_TID, "(port)video_out_TID");
    sc_trace(mVcdFile, video_out_TDEST, "(port)video_out_TDEST");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, video_in_TVALID, "(port)video_in_TVALID");
    sc_trace(mVcdFile, video_in_TREADY, "(port)video_in_TREADY");
    sc_trace(mVcdFile, video_out_TVALID, "(port)video_out_TVALID");
    sc_trace(mVcdFile, video_out_TREADY, "(port)video_out_TREADY");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, Block_proc_U0_ap_start, "Block_proc_U0_ap_start");
    sc_trace(mVcdFile, Block_proc_U0_ap_done, "Block_proc_U0_ap_done");
    sc_trace(mVcdFile, Block_proc_U0_ap_continue, "Block_proc_U0_ap_continue");
    sc_trace(mVcdFile, Block_proc_U0_ap_idle, "Block_proc_U0_ap_idle");
    sc_trace(mVcdFile, Block_proc_U0_ap_ready, "Block_proc_U0_ap_ready");
    sc_trace(mVcdFile, Block_proc_U0_start_out, "Block_proc_U0_start_out");
    sc_trace(mVcdFile, Block_proc_U0_start_write, "Block_proc_U0_start_write");
    sc_trace(mVcdFile, Block_proc_U0_img_0_rows_V_out_din, "Block_proc_U0_img_0_rows_V_out_din");
    sc_trace(mVcdFile, Block_proc_U0_img_0_rows_V_out_write, "Block_proc_U0_img_0_rows_V_out_write");
    sc_trace(mVcdFile, Block_proc_U0_img_0_cols_V_out_din, "Block_proc_U0_img_0_cols_V_out_din");
    sc_trace(mVcdFile, Block_proc_U0_img_0_cols_V_out_write, "Block_proc_U0_img_0_cols_V_out_write");
    sc_trace(mVcdFile, Block_proc_U0_img_3_rows_V_out_din, "Block_proc_U0_img_3_rows_V_out_din");
    sc_trace(mVcdFile, Block_proc_U0_img_3_rows_V_out_write, "Block_proc_U0_img_3_rows_V_out_write");
    sc_trace(mVcdFile, Block_proc_U0_img_3_cols_V_out_din, "Block_proc_U0_img_3_cols_V_out_din");
    sc_trace(mVcdFile, Block_proc_U0_img_3_cols_V_out_write, "Block_proc_U0_img_3_cols_V_out_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_start, "AXIvideo2Mat_U0_ap_start");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_done, "AXIvideo2Mat_U0_ap_done");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_continue, "AXIvideo2Mat_U0_ap_continue");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_idle, "AXIvideo2Mat_U0_ap_idle");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_ready, "AXIvideo2Mat_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_start_out, "AXIvideo2Mat_U0_start_out");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_start_write, "AXIvideo2Mat_U0_start_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_video_in_TREADY, "AXIvideo2Mat_U0_video_in_TREADY");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_read, "AXIvideo2Mat_U0_img_rows_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_read, "AXIvideo2Mat_U0_img_cols_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_0_V_din, "AXIvideo2Mat_U0_img_data_stream_0_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_0_V_write, "AXIvideo2Mat_U0_img_data_stream_0_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_1_V_din, "AXIvideo2Mat_U0_img_data_stream_1_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_1_V_write, "AXIvideo2Mat_U0_img_data_stream_1_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_2_V_din, "AXIvideo2Mat_U0_img_data_stream_2_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_2_V_write, "AXIvideo2Mat_U0_img_data_stream_2_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_out_din, "AXIvideo2Mat_U0_img_rows_V_out_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_out_write, "AXIvideo2Mat_U0_img_rows_V_out_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_out_din, "AXIvideo2Mat_U0_img_cols_V_out_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_out_write, "AXIvideo2Mat_U0_img_cols_V_out_write");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_start, "CvtColor_1_U0_ap_start");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_done, "CvtColor_1_U0_ap_done");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_continue, "CvtColor_1_U0_ap_continue");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_idle, "CvtColor_1_U0_ap_idle");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_ready, "CvtColor_1_U0_ap_ready");
    sc_trace(mVcdFile, CvtColor_1_U0_start_out, "CvtColor_1_U0_start_out");
    sc_trace(mVcdFile, CvtColor_1_U0_start_write, "CvtColor_1_U0_start_write");
    sc_trace(mVcdFile, CvtColor_1_U0_p_src_rows_V_read, "CvtColor_1_U0_p_src_rows_V_read");
    sc_trace(mVcdFile, CvtColor_1_U0_p_src_cols_V_read, "CvtColor_1_U0_p_src_cols_V_read");
    sc_trace(mVcdFile, CvtColor_1_U0_p_src_data_stream_0_V_read, "CvtColor_1_U0_p_src_data_stream_0_V_read");
    sc_trace(mVcdFile, CvtColor_1_U0_p_src_data_stream_1_V_read, "CvtColor_1_U0_p_src_data_stream_1_V_read");
    sc_trace(mVcdFile, CvtColor_1_U0_p_src_data_stream_2_V_read, "CvtColor_1_U0_p_src_data_stream_2_V_read");
    sc_trace(mVcdFile, CvtColor_1_U0_p_dst_data_stream_V_din, "CvtColor_1_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, CvtColor_1_U0_p_dst_data_stream_V_write, "CvtColor_1_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_start, "GaussianBlur_U0_ap_start");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_done, "GaussianBlur_U0_ap_done");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_continue, "GaussianBlur_U0_ap_continue");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_idle, "GaussianBlur_U0_ap_idle");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_ready, "GaussianBlur_U0_ap_ready");
    sc_trace(mVcdFile, GaussianBlur_U0_p_src_data_stream_V_read, "GaussianBlur_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, GaussianBlur_U0_p_dst_data_stream_V_din, "GaussianBlur_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, GaussianBlur_U0_p_dst_data_stream_V_write, "GaussianBlur_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, Threshold_U0_ap_start, "Threshold_U0_ap_start");
    sc_trace(mVcdFile, Threshold_U0_ap_done, "Threshold_U0_ap_done");
    sc_trace(mVcdFile, Threshold_U0_ap_continue, "Threshold_U0_ap_continue");
    sc_trace(mVcdFile, Threshold_U0_ap_idle, "Threshold_U0_ap_idle");
    sc_trace(mVcdFile, Threshold_U0_ap_ready, "Threshold_U0_ap_ready");
    sc_trace(mVcdFile, Threshold_U0_start_out, "Threshold_U0_start_out");
    sc_trace(mVcdFile, Threshold_U0_start_write, "Threshold_U0_start_write");
    sc_trace(mVcdFile, Threshold_U0_src_data_stream_V_read, "Threshold_U0_src_data_stream_V_read");
    sc_trace(mVcdFile, Threshold_U0_dst_rows_V_read, "Threshold_U0_dst_rows_V_read");
    sc_trace(mVcdFile, Threshold_U0_dst_cols_V_read, "Threshold_U0_dst_cols_V_read");
    sc_trace(mVcdFile, Threshold_U0_dst_data_stream_V_din, "Threshold_U0_dst_data_stream_V_din");
    sc_trace(mVcdFile, Threshold_U0_dst_data_stream_V_write, "Threshold_U0_dst_data_stream_V_write");
    sc_trace(mVcdFile, Threshold_U0_dst_rows_V_out_din, "Threshold_U0_dst_rows_V_out_din");
    sc_trace(mVcdFile, Threshold_U0_dst_rows_V_out_write, "Threshold_U0_dst_rows_V_out_write");
    sc_trace(mVcdFile, Threshold_U0_dst_cols_V_out_din, "Threshold_U0_dst_cols_V_out_din");
    sc_trace(mVcdFile, Threshold_U0_dst_cols_V_out_write, "Threshold_U0_dst_cols_V_out_write");
    sc_trace(mVcdFile, CvtColor_U0_ap_start, "CvtColor_U0_ap_start");
    sc_trace(mVcdFile, CvtColor_U0_ap_done, "CvtColor_U0_ap_done");
    sc_trace(mVcdFile, CvtColor_U0_ap_continue, "CvtColor_U0_ap_continue");
    sc_trace(mVcdFile, CvtColor_U0_ap_idle, "CvtColor_U0_ap_idle");
    sc_trace(mVcdFile, CvtColor_U0_ap_ready, "CvtColor_U0_ap_ready");
    sc_trace(mVcdFile, CvtColor_U0_start_out, "CvtColor_U0_start_out");
    sc_trace(mVcdFile, CvtColor_U0_start_write, "CvtColor_U0_start_write");
    sc_trace(mVcdFile, CvtColor_U0_p_src_rows_V_read, "CvtColor_U0_p_src_rows_V_read");
    sc_trace(mVcdFile, CvtColor_U0_p_src_cols_V_read, "CvtColor_U0_p_src_cols_V_read");
    sc_trace(mVcdFile, CvtColor_U0_p_src_data_stream_V_read, "CvtColor_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, CvtColor_U0_p_dst_data_stream_0_V_din, "CvtColor_U0_p_dst_data_stream_0_V_din");
    sc_trace(mVcdFile, CvtColor_U0_p_dst_data_stream_0_V_write, "CvtColor_U0_p_dst_data_stream_0_V_write");
    sc_trace(mVcdFile, CvtColor_U0_p_dst_data_stream_1_V_din, "CvtColor_U0_p_dst_data_stream_1_V_din");
    sc_trace(mVcdFile, CvtColor_U0_p_dst_data_stream_1_V_write, "CvtColor_U0_p_dst_data_stream_1_V_write");
    sc_trace(mVcdFile, CvtColor_U0_p_dst_data_stream_2_V_din, "CvtColor_U0_p_dst_data_stream_2_V_din");
    sc_trace(mVcdFile, CvtColor_U0_p_dst_data_stream_2_V_write, "CvtColor_U0_p_dst_data_stream_2_V_write");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_start, "Mat2AXIvideo_U0_ap_start");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_done, "Mat2AXIvideo_U0_ap_done");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_continue, "Mat2AXIvideo_U0_ap_continue");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_idle, "Mat2AXIvideo_U0_ap_idle");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_ready, "Mat2AXIvideo_U0_ap_ready");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_0_V_read, "Mat2AXIvideo_U0_img_data_stream_0_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_1_V_read, "Mat2AXIvideo_U0_img_data_stream_1_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_2_V_read, "Mat2AXIvideo_U0_img_data_stream_2_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_video_out_TDATA, "Mat2AXIvideo_U0_video_out_TDATA");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_video_out_TVALID, "Mat2AXIvideo_U0_video_out_TVALID");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_video_out_TKEEP, "Mat2AXIvideo_U0_video_out_TKEEP");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_video_out_TSTRB, "Mat2AXIvideo_U0_video_out_TSTRB");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_video_out_TUSER, "Mat2AXIvideo_U0_video_out_TUSER");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_video_out_TLAST, "Mat2AXIvideo_U0_video_out_TLAST");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_video_out_TID, "Mat2AXIvideo_U0_video_out_TID");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_video_out_TDEST, "Mat2AXIvideo_U0_video_out_TDEST");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, img_0_rows_V_c_full_n, "img_0_rows_V_c_full_n");
    sc_trace(mVcdFile, img_0_rows_V_c_dout, "img_0_rows_V_c_dout");
    sc_trace(mVcdFile, img_0_rows_V_c_empty_n, "img_0_rows_V_c_empty_n");
    sc_trace(mVcdFile, img_0_cols_V_c_full_n, "img_0_cols_V_c_full_n");
    sc_trace(mVcdFile, img_0_cols_V_c_dout, "img_0_cols_V_c_dout");
    sc_trace(mVcdFile, img_0_cols_V_c_empty_n, "img_0_cols_V_c_empty_n");
    sc_trace(mVcdFile, img_3_rows_V_c_full_n, "img_3_rows_V_c_full_n");
    sc_trace(mVcdFile, img_3_rows_V_c_dout, "img_3_rows_V_c_dout");
    sc_trace(mVcdFile, img_3_rows_V_c_empty_n, "img_3_rows_V_c_empty_n");
    sc_trace(mVcdFile, img_3_cols_V_c_full_n, "img_3_cols_V_c_full_n");
    sc_trace(mVcdFile, img_3_cols_V_c_dout, "img_3_cols_V_c_dout");
    sc_trace(mVcdFile, img_3_cols_V_c_empty_n, "img_3_cols_V_c_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_0_full_n, "img_0_data_stream_0_full_n");
    sc_trace(mVcdFile, img_0_data_stream_0_dout, "img_0_data_stream_0_dout");
    sc_trace(mVcdFile, img_0_data_stream_0_empty_n, "img_0_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_1_full_n, "img_0_data_stream_1_full_n");
    sc_trace(mVcdFile, img_0_data_stream_1_dout, "img_0_data_stream_1_dout");
    sc_trace(mVcdFile, img_0_data_stream_1_empty_n, "img_0_data_stream_1_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_2_full_n, "img_0_data_stream_2_full_n");
    sc_trace(mVcdFile, img_0_data_stream_2_dout, "img_0_data_stream_2_dout");
    sc_trace(mVcdFile, img_0_data_stream_2_empty_n, "img_0_data_stream_2_empty_n");
    sc_trace(mVcdFile, img_0_rows_V_c14_full_n, "img_0_rows_V_c14_full_n");
    sc_trace(mVcdFile, img_0_rows_V_c14_dout, "img_0_rows_V_c14_dout");
    sc_trace(mVcdFile, img_0_rows_V_c14_empty_n, "img_0_rows_V_c14_empty_n");
    sc_trace(mVcdFile, img_0_cols_V_c15_full_n, "img_0_cols_V_c15_full_n");
    sc_trace(mVcdFile, img_0_cols_V_c15_dout, "img_0_cols_V_c15_dout");
    sc_trace(mVcdFile, img_0_cols_V_c15_empty_n, "img_0_cols_V_c15_empty_n");
    sc_trace(mVcdFile, img_1_data_stream_0_full_n, "img_1_data_stream_0_full_n");
    sc_trace(mVcdFile, img_1_data_stream_0_dout, "img_1_data_stream_0_dout");
    sc_trace(mVcdFile, img_1_data_stream_0_empty_n, "img_1_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_2_data_stream_0_full_n, "img_2_data_stream_0_full_n");
    sc_trace(mVcdFile, img_2_data_stream_0_dout, "img_2_data_stream_0_dout");
    sc_trace(mVcdFile, img_2_data_stream_0_empty_n, "img_2_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_3_data_stream_0_full_n, "img_3_data_stream_0_full_n");
    sc_trace(mVcdFile, img_3_data_stream_0_dout, "img_3_data_stream_0_dout");
    sc_trace(mVcdFile, img_3_data_stream_0_empty_n, "img_3_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_3_rows_V_c16_full_n, "img_3_rows_V_c16_full_n");
    sc_trace(mVcdFile, img_3_rows_V_c16_dout, "img_3_rows_V_c16_dout");
    sc_trace(mVcdFile, img_3_rows_V_c16_empty_n, "img_3_rows_V_c16_empty_n");
    sc_trace(mVcdFile, img_3_cols_V_c17_full_n, "img_3_cols_V_c17_full_n");
    sc_trace(mVcdFile, img_3_cols_V_c17_dout, "img_3_cols_V_c17_dout");
    sc_trace(mVcdFile, img_3_cols_V_c17_empty_n, "img_3_cols_V_c17_empty_n");
    sc_trace(mVcdFile, img_4_data_stream_0_full_n, "img_4_data_stream_0_full_n");
    sc_trace(mVcdFile, img_4_data_stream_0_dout, "img_4_data_stream_0_dout");
    sc_trace(mVcdFile, img_4_data_stream_0_empty_n, "img_4_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_4_data_stream_1_full_n, "img_4_data_stream_1_full_n");
    sc_trace(mVcdFile, img_4_data_stream_1_dout, "img_4_data_stream_1_dout");
    sc_trace(mVcdFile, img_4_data_stream_1_empty_n, "img_4_data_stream_1_empty_n");
    sc_trace(mVcdFile, img_4_data_stream_2_full_n, "img_4_data_stream_2_full_n");
    sc_trace(mVcdFile, img_4_data_stream_2_dout, "img_4_data_stream_2_dout");
    sc_trace(mVcdFile, img_4_data_stream_2_empty_n, "img_4_data_stream_2_empty_n");
    sc_trace(mVcdFile, ap_sync_done, "ap_sync_done");
    sc_trace(mVcdFile, ap_sync_ready, "ap_sync_ready");
    sc_trace(mVcdFile, ap_sync_reg_Block_proc_U0_ap_ready, "ap_sync_reg_Block_proc_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_Block_proc_U0_ap_ready, "ap_sync_Block_proc_U0_ap_ready");
    sc_trace(mVcdFile, Block_proc_U0_ap_ready_count, "Block_proc_U0_ap_ready_count");
    sc_trace(mVcdFile, ap_sync_reg_AXIvideo2Mat_U0_ap_ready, "ap_sync_reg_AXIvideo2Mat_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_AXIvideo2Mat_U0_ap_ready, "ap_sync_AXIvideo2Mat_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_ready_count, "AXIvideo2Mat_U0_ap_ready_count");
    sc_trace(mVcdFile, start_for_Threshold_U0_din, "start_for_Threshold_U0_din");
    sc_trace(mVcdFile, start_for_Threshold_U0_full_n, "start_for_Threshold_U0_full_n");
    sc_trace(mVcdFile, start_for_Threshold_U0_dout, "start_for_Threshold_U0_dout");
    sc_trace(mVcdFile, start_for_Threshold_U0_empty_n, "start_for_Threshold_U0_empty_n");
    sc_trace(mVcdFile, start_for_CvtColor_1_U0_din, "start_for_CvtColor_1_U0_din");
    sc_trace(mVcdFile, start_for_CvtColor_1_U0_full_n, "start_for_CvtColor_1_U0_full_n");
    sc_trace(mVcdFile, start_for_CvtColor_1_U0_dout, "start_for_CvtColor_1_U0_dout");
    sc_trace(mVcdFile, start_for_CvtColor_1_U0_empty_n, "start_for_CvtColor_1_U0_empty_n");
    sc_trace(mVcdFile, start_for_GaussianBlur_U0_din, "start_for_GaussianBlur_U0_din");
    sc_trace(mVcdFile, start_for_GaussianBlur_U0_full_n, "start_for_GaussianBlur_U0_full_n");
    sc_trace(mVcdFile, start_for_GaussianBlur_U0_dout, "start_for_GaussianBlur_U0_dout");
    sc_trace(mVcdFile, start_for_GaussianBlur_U0_empty_n, "start_for_GaussianBlur_U0_empty_n");
    sc_trace(mVcdFile, GaussianBlur_U0_start_full_n, "GaussianBlur_U0_start_full_n");
    sc_trace(mVcdFile, GaussianBlur_U0_start_write, "GaussianBlur_U0_start_write");
    sc_trace(mVcdFile, start_for_CvtColor_U0_din, "start_for_CvtColor_U0_din");
    sc_trace(mVcdFile, start_for_CvtColor_U0_full_n, "start_for_CvtColor_U0_full_n");
    sc_trace(mVcdFile, start_for_CvtColor_U0_dout, "start_for_CvtColor_U0_dout");
    sc_trace(mVcdFile, start_for_CvtColor_U0_empty_n, "start_for_CvtColor_U0_empty_n");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_din, "start_for_Mat2AXIvideo_U0_din");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_full_n, "start_for_Mat2AXIvideo_U0_full_n");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_dout, "start_for_Mat2AXIvideo_U0_dout");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_empty_n, "start_for_Mat2AXIvideo_U0_empty_n");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_start_full_n, "Mat2AXIvideo_U0_start_full_n");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_start_write, "Mat2AXIvideo_U0_start_write");
#endif

    }
    mHdltvinHandle.open("filter.hdltvin.dat");
    mHdltvoutHandle.open("filter.hdltvout.dat");
}

filter::~filter() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete Block_proc_U0;
    delete AXIvideo2Mat_U0;
    delete CvtColor_1_U0;
    delete GaussianBlur_U0;
    delete Threshold_U0;
    delete CvtColor_U0;
    delete Mat2AXIvideo_U0;
    delete img_0_rows_V_c_U;
    delete img_0_cols_V_c_U;
    delete img_3_rows_V_c_U;
    delete img_3_cols_V_c_U;
    delete img_0_data_stream_0_U;
    delete img_0_data_stream_1_U;
    delete img_0_data_stream_2_U;
    delete img_0_rows_V_c14_U;
    delete img_0_cols_V_c15_U;
    delete img_1_data_stream_0_U;
    delete img_2_data_stream_0_U;
    delete img_3_data_stream_0_U;
    delete img_3_rows_V_c16_U;
    delete img_3_cols_V_c17_U;
    delete img_4_data_stream_0_U;
    delete img_4_data_stream_1_U;
    delete img_4_data_stream_2_U;
    delete start_for_Threshoyd2_U;
    delete start_for_CvtColozec_U;
    delete start_for_GaussiaAem_U;
    delete start_for_CvtColoBew_U;
    delete start_for_Mat2AXICeG_U;
}

void filter::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void filter::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()) && 
         esl_seteq<1,1,1>(AXIvideo2Mat_U0_ap_ready.read(), ap_const_logic_0))) {
        AXIvideo2Mat_U0_ap_ready_count = (!AXIvideo2Mat_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(AXIvideo2Mat_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_sync_ready.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, AXIvideo2Mat_U0_ap_ready.read()))) {
        AXIvideo2Mat_U0_ap_ready_count = (!AXIvideo2Mat_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(AXIvideo2Mat_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ((esl_seteq<1,1,1>(Block_proc_U0_ap_ready.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()))) {
        Block_proc_U0_ap_ready_count = (!Block_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_proc_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(Block_proc_U0_ap_ready.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_sync_ready.read(), ap_const_logic_0))) {
        Block_proc_U0_ap_ready_count = (!Block_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_proc_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_AXIvideo2Mat_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_AXIvideo2Mat_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_AXIvideo2Mat_U0_ap_ready = ap_sync_AXIvideo2Mat_U0_ap_ready.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_Block_proc_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_Block_proc_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_Block_proc_U0_ap_ready = ap_sync_Block_proc_U0_ap_ready.read();
        }
    }
}

void filter::thread_AXIvideo2Mat_U0_ap_continue() {
    AXIvideo2Mat_U0_ap_continue = ap_const_logic_1;
}

void filter::thread_AXIvideo2Mat_U0_ap_start() {
    AXIvideo2Mat_U0_ap_start = (ap_start.read() & (ap_sync_reg_AXIvideo2Mat_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void filter::thread_Block_proc_U0_ap_continue() {
    Block_proc_U0_ap_continue = ap_const_logic_1;
}

void filter::thread_Block_proc_U0_ap_start() {
    Block_proc_U0_ap_start = (ap_start.read() & (ap_sync_reg_Block_proc_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void filter::thread_CvtColor_1_U0_ap_continue() {
    CvtColor_1_U0_ap_continue = ap_const_logic_1;
}

void filter::thread_CvtColor_1_U0_ap_start() {
    CvtColor_1_U0_ap_start = start_for_CvtColor_1_U0_empty_n.read();
}

void filter::thread_CvtColor_U0_ap_continue() {
    CvtColor_U0_ap_continue = ap_const_logic_1;
}

void filter::thread_CvtColor_U0_ap_start() {
    CvtColor_U0_ap_start = start_for_CvtColor_U0_empty_n.read();
}

void filter::thread_GaussianBlur_U0_ap_continue() {
    GaussianBlur_U0_ap_continue = ap_const_logic_1;
}

void filter::thread_GaussianBlur_U0_ap_start() {
    GaussianBlur_U0_ap_start = start_for_GaussianBlur_U0_empty_n.read();
}

void filter::thread_GaussianBlur_U0_start_full_n() {
    GaussianBlur_U0_start_full_n = ap_const_logic_1;
}

void filter::thread_GaussianBlur_U0_start_write() {
    GaussianBlur_U0_start_write = ap_const_logic_0;
}

void filter::thread_Mat2AXIvideo_U0_ap_continue() {
    Mat2AXIvideo_U0_ap_continue = ap_const_logic_1;
}

void filter::thread_Mat2AXIvideo_U0_ap_start() {
    Mat2AXIvideo_U0_ap_start = start_for_Mat2AXIvideo_U0_empty_n.read();
}

void filter::thread_Mat2AXIvideo_U0_start_full_n() {
    Mat2AXIvideo_U0_start_full_n = ap_const_logic_1;
}

void filter::thread_Mat2AXIvideo_U0_start_write() {
    Mat2AXIvideo_U0_start_write = ap_const_logic_0;
}

void filter::thread_Threshold_U0_ap_continue() {
    Threshold_U0_ap_continue = ap_const_logic_1;
}

void filter::thread_Threshold_U0_ap_start() {
    Threshold_U0_ap_start = start_for_Threshold_U0_empty_n.read();
}

void filter::thread_ap_done() {
    ap_done = Mat2AXIvideo_U0_ap_done.read();
}

void filter::thread_ap_idle() {
    ap_idle = (Block_proc_U0_ap_idle.read() & AXIvideo2Mat_U0_ap_idle.read() & CvtColor_1_U0_ap_idle.read() & GaussianBlur_U0_ap_idle.read() & Threshold_U0_ap_idle.read() & CvtColor_U0_ap_idle.read() & Mat2AXIvideo_U0_ap_idle.read());
}

void filter::thread_ap_ready() {
    ap_ready = ap_sync_ready.read();
}

void filter::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void filter::thread_ap_sync_AXIvideo2Mat_U0_ap_ready() {
    ap_sync_AXIvideo2Mat_U0_ap_ready = (AXIvideo2Mat_U0_ap_ready.read() | ap_sync_reg_AXIvideo2Mat_U0_ap_ready.read());
}

void filter::thread_ap_sync_Block_proc_U0_ap_ready() {
    ap_sync_Block_proc_U0_ap_ready = (Block_proc_U0_ap_ready.read() | ap_sync_reg_Block_proc_U0_ap_ready.read());
}

void filter::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_1;
}

void filter::thread_ap_sync_done() {
    ap_sync_done = Mat2AXIvideo_U0_ap_done.read();
}

void filter::thread_ap_sync_ready() {
    ap_sync_ready = (ap_sync_Block_proc_U0_ap_ready.read() & ap_sync_AXIvideo2Mat_U0_ap_ready.read());
}

void filter::thread_start_for_CvtColor_1_U0_din() {
    start_for_CvtColor_1_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void filter::thread_start_for_CvtColor_U0_din() {
    start_for_CvtColor_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void filter::thread_start_for_GaussianBlur_U0_din() {
    start_for_GaussianBlur_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void filter::thread_start_for_Mat2AXIvideo_U0_din() {
    start_for_Mat2AXIvideo_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void filter::thread_start_for_Threshold_U0_din() {
    start_for_Threshold_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void filter::thread_video_in_TREADY() {
    video_in_TREADY = AXIvideo2Mat_U0_video_in_TREADY.read();
}

void filter::thread_video_out_TDATA() {
    video_out_TDATA = Mat2AXIvideo_U0_video_out_TDATA.read();
}

void filter::thread_video_out_TDEST() {
    video_out_TDEST = Mat2AXIvideo_U0_video_out_TDEST.read();
}

void filter::thread_video_out_TID() {
    video_out_TID = Mat2AXIvideo_U0_video_out_TID.read();
}

void filter::thread_video_out_TKEEP() {
    video_out_TKEEP = Mat2AXIvideo_U0_video_out_TKEEP.read();
}

void filter::thread_video_out_TLAST() {
    video_out_TLAST = Mat2AXIvideo_U0_video_out_TLAST.read();
}

void filter::thread_video_out_TSTRB() {
    video_out_TSTRB = Mat2AXIvideo_U0_video_out_TSTRB.read();
}

void filter::thread_video_out_TUSER() {
    video_out_TUSER = Mat2AXIvideo_U0_video_out_TUSER.read();
}

void filter::thread_video_out_TVALID() {
    video_out_TVALID = Mat2AXIvideo_U0_video_out_TVALID.read();
}

void filter::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"video_in_TDATA\" :  \"" << video_in_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TKEEP\" :  \"" << video_in_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TSTRB\" :  \"" << video_in_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TUSER\" :  \"" << video_in_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TLAST\" :  \"" << video_in_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TID\" :  \"" << video_in_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TDEST\" :  \"" << video_in_TDEST.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"video_out_TDATA\" :  \"" << video_out_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TKEEP\" :  \"" << video_out_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TSTRB\" :  \"" << video_out_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TUSER\" :  \"" << video_out_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TLAST\" :  \"" << video_out_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TID\" :  \"" << video_out_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TDEST\" :  \"" << video_out_TDEST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TVALID\" :  \"" << video_in_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_in_TREADY\" :  \"" << video_in_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TVALID\" :  \"" << video_out_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_out_TREADY\" :  \"" << video_out_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

