// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _doGain_HH_
#define _doGain_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct doGain : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_lv<32> > inStream_TDATA;
    sc_in< sc_logic > inStream_TVALID;
    sc_out< sc_logic > inStream_TREADY;
    sc_in< sc_lv<4> > inStream_TKEEP;
    sc_in< sc_lv<4> > inStream_TSTRB;
    sc_in< sc_lv<2> > inStream_TUSER;
    sc_in< sc_lv<1> > inStream_TLAST;
    sc_in< sc_lv<5> > inStream_TID;
    sc_in< sc_lv<6> > inStream_TDEST;
    sc_out< sc_lv<32> > outStream_TDATA;
    sc_out< sc_logic > outStream_TVALID;
    sc_in< sc_logic > outStream_TREADY;
    sc_out< sc_lv<4> > outStream_TKEEP;
    sc_out< sc_lv<4> > outStream_TSTRB;
    sc_out< sc_lv<2> > outStream_TUSER;
    sc_out< sc_lv<1> > outStream_TLAST;
    sc_out< sc_lv<5> > outStream_TID;
    sc_out< sc_lv<6> > outStream_TDEST;


    // Module declarations
    doGain(sc_module_name name);
    SC_HAS_PROCESS(doGain);

    ~doGain();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    regslice_both<32>* regslice_both_inStream_V_data_V_U;
    regslice_both<4>* regslice_both_inStream_V_keep_V_U;
    regslice_both<4>* regslice_both_inStream_V_strb_V_U;
    regslice_both<2>* regslice_both_inStream_V_user_V_U;
    regslice_both<1>* regslice_both_inStream_V_last_V_U;
    regslice_both<5>* regslice_both_inStream_V_id_V_U;
    regslice_both<6>* regslice_both_inStream_V_dest_V_U;
    regslice_both<32>* regslice_both_outStream_V_data_V_U;
    regslice_both<4>* regslice_both_outStream_V_keep_V_U;
    regslice_both<4>* regslice_both_outStream_V_strb_V_U;
    regslice_both<2>* regslice_both_outStream_V_user_V_U;
    regslice_both<1>* regslice_both_outStream_V_last_V_U;
    regslice_both<5>* regslice_both_outStream_V_id_V_U;
    regslice_both<6>* regslice_both_outStream_V_dest_V_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > inStream_TDATA_blk_n;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > icmp_ln13_fu_126_p2;
    sc_signal< sc_logic > outStream_TDATA_blk_n;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_lv<1> > icmp_ln13_reg_172;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_lv<1> > icmp_ln13_reg_172_pp0_iter1_reg;
    sc_signal< sc_lv<10> > idx_0_reg_115;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state3_io;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state4_io;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<10> > idx_fu_132_p2;
    sc_signal< sc_lv<32> > tmp_data_V_reg_181;
    sc_signal< sc_lv<4> > tmp_keep_V_reg_186;
    sc_signal< sc_lv<4> > tmp_strb_V_reg_191;
    sc_signal< sc_lv<2> > tmp_user_V_reg_196;
    sc_signal< sc_lv<1> > tmp_last_V_reg_201;
    sc_signal< sc_lv<5> > tmp_id_V_reg_206;
    sc_signal< sc_lv<6> > tmp_dest_V_reg_211;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state2;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > regslice_both_outStream_V_data_V_U_apdone_blk;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    sc_signal< sc_logic > regslice_both_inStream_V_data_V_U_apdone_blk;
    sc_signal< sc_lv<32> > inStream_TDATA_int;
    sc_signal< sc_logic > inStream_TVALID_int;
    sc_signal< sc_logic > inStream_TREADY_int;
    sc_signal< sc_logic > regslice_both_inStream_V_data_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_inStream_V_keep_V_U_apdone_blk;
    sc_signal< sc_lv<4> > inStream_TKEEP_int;
    sc_signal< sc_logic > regslice_both_inStream_V_keep_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_inStream_V_keep_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_inStream_V_strb_V_U_apdone_blk;
    sc_signal< sc_lv<4> > inStream_TSTRB_int;
    sc_signal< sc_logic > regslice_both_inStream_V_strb_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_inStream_V_strb_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_inStream_V_user_V_U_apdone_blk;
    sc_signal< sc_lv<2> > inStream_TUSER_int;
    sc_signal< sc_logic > regslice_both_inStream_V_user_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_inStream_V_user_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_inStream_V_last_V_U_apdone_blk;
    sc_signal< sc_lv<1> > inStream_TLAST_int;
    sc_signal< sc_logic > regslice_both_inStream_V_last_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_inStream_V_last_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_inStream_V_id_V_U_apdone_blk;
    sc_signal< sc_lv<5> > inStream_TID_int;
    sc_signal< sc_logic > regslice_both_inStream_V_id_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_inStream_V_id_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_inStream_V_dest_V_U_apdone_blk;
    sc_signal< sc_lv<6> > inStream_TDEST_int;
    sc_signal< sc_logic > regslice_both_inStream_V_dest_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_inStream_V_dest_V_U_ack_in;
    sc_signal< sc_lv<32> > outStream_TDATA_int;
    sc_signal< sc_logic > outStream_TVALID_int;
    sc_signal< sc_logic > outStream_TREADY_int;
    sc_signal< sc_logic > regslice_both_outStream_V_data_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_outStream_V_keep_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_outStream_V_keep_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_outStream_V_keep_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_outStream_V_strb_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_outStream_V_strb_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_outStream_V_strb_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_outStream_V_user_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_outStream_V_user_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_outStream_V_user_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_outStream_V_last_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_outStream_V_last_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_outStream_V_last_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_outStream_V_id_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_outStream_V_id_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_outStream_V_id_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_outStream_V_dest_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_outStream_V_dest_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_outStream_V_dest_V_U_vld_out;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_pp0_stage0;
    static const sc_lv<3> ap_ST_fsm_state5;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<10> ap_const_lv10_3E8;
    static const sc_lv<10> ap_const_lv10_1;
    static const sc_lv<32> ap_const_lv32_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state5();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state2_pp0_stage0_iter0();
    void thread_ap_block_state3_io();
    void thread_ap_block_state3_pp0_stage0_iter1();
    void thread_ap_block_state4_io();
    void thread_ap_block_state4_pp0_stage0_iter2();
    void thread_ap_condition_pp0_exit_iter0_state2();
    void thread_ap_enable_pp0();
    void thread_ap_idle_pp0();
    void thread_ap_rst_n_inv();
    void thread_icmp_ln13_fu_126_p2();
    void thread_idx_fu_132_p2();
    void thread_inStream_TDATA_blk_n();
    void thread_inStream_TREADY();
    void thread_inStream_TREADY_int();
    void thread_outStream_TDATA_blk_n();
    void thread_outStream_TDATA_int();
    void thread_outStream_TVALID();
    void thread_outStream_TVALID_int();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
